//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMWholesale.OldDAS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://protal.liquidmotors.com", ConfigurationName="OldDAS.DASSoap")]
    public interface DASSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalytics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetAnalytics(string SessionID, int DealerGroup, int DealerID, string Listing, int StockType, int Status, int IconStatus, int PrintStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalytics", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsAsync(string SessionID, int DealerGroup, int DealerID, string Listing, int StockType, int Status, int IconStatus, int PrintStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsReRun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetAnalyticsReRun(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsReRun", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsReRunAsync(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsDetailed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetAnalyticsDetailed(string SessionID, string Listing, int Distance, int Certified, int StyleSearch, string Auction, int FilterType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsDetailed", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsDetailedAsync(string SessionID, string Listing, int Distance, int Certified, int StyleSearch, string Auction, int FilterType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsELink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetAnalyticsELink(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsELink", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsELinkAsync(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsFeatures", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetAnalyticsFeatures(string SessionID, int Operation, string Year, string Make, string Model, string Series, string Style);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsFeatures", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsFeaturesAsync(string SessionID, int Operation, string Year, string Make, string Model, string Series, string Style);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsDefine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetAnalyticsDefine(string SessionID, int Operation, string Listing, int Mode, int Item, string Feature);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsDefine", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsDefineAsync(string SessionID, int Operation, string Listing, int Mode, int Item, string Feature);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetAnalyticsOptions(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsOptions", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsOptionsAsync(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetAnalyticsUpdate(string SessionID, int Operation, string Listing, string StockNumber, string Miles, string Cost, string ListPrice, int ImportOverride, string InternetPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsUpdateAsync(string SessionID, int Operation, string Listing, string StockNumber, string Miles, string Cost, string ListPrice, int ImportOverride, string InternetPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsDASInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetAnalyticsDASInventory(
                    string SessionID, 
                    int Operation, 
                    int Dealer, 
                    string StockNumber, 
                    string VIN, 
                    string MotorYear, 
                    int Miles, 
                    int InvCost, 
                    int ListPrice, 
                    string MakeStr, 
                    string ModelStr, 
                    string StyleStr, 
                    string StyleID, 
                    string sMode, 
                    int DrillDown, 
                    int StockType, 
                    int Status, 
                    int ImportOverride, 
                    int InternetPrice, 
                    int kVehicleClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsDASInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsDASInventoryAsync(
                    string SessionID, 
                    int Operation, 
                    int Dealer, 
                    string StockNumber, 
                    string VIN, 
                    string MotorYear, 
                    int Miles, 
                    int InvCost, 
                    int ListPrice, 
                    string MakeStr, 
                    string ModelStr, 
                    string StyleStr, 
                    string StyleID, 
                    string sMode, 
                    int DrillDown, 
                    int StockType, 
                    int Status, 
                    int ImportOverride, 
                    int InternetPrice, 
                    int kVehicleClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsCommit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetAnalyticsCommit(string SessionID, int Operation, string Listing, string StockNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsCommit", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsCommitAsync(string SessionID, int Operation, string Listing, string StockNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetAnalyticsDelete(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetAnalyticsDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsDeleteAsync(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetAnalyticsInfo(string SessionID, int Operation, string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetAnalyticsInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsInfoAsync(string SessionID, int Operation, string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetBBValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetBBValues(string SessionID, int Operation, string VIN, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetBBValues", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetBBValuesAsync(string SessionID, int Operation, string VIN, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetUpdateInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetUpdateInventory(
                    string SessionID, 
                    string Listing, 
                    string StockNumber, 
                    string VIN, 
                    string Miles, 
                    string InvCost, 
                    string ListPrice, 
                    string Year, 
                    string Make, 
                    string Model, 
                    string Style, 
                    string StyleID, 
                    string Mode, 
                    int DrillDown, 
                    int StockType, 
                    int Status, 
                    int ImportOverride);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetUpdateInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetUpdateInventoryAsync(
                    string SessionID, 
                    string Listing, 
                    string StockNumber, 
                    string VIN, 
                    string Miles, 
                    string InvCost, 
                    string ListPrice, 
                    string Year, 
                    string Make, 
                    string Model, 
                    string Style, 
                    string StyleID, 
                    string Mode, 
                    int DrillDown, 
                    int StockType, 
                    int Status, 
                    int ImportOverride);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetDASChromeYear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetDASChromeYear(string SessionID, int Operation, string MotorYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetDASChromeYear", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetDASChromeYearAsync(string SessionID, int Operation, string MotorYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetDASChromeStyles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetDASChromeStyles(string SessionID, int Operation, string Vin, string MotorYear, string MakeStr, string ModelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetDASChromeStyles", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetDASChromeStylesAsync(string SessionID, int Operation, string Vin, string MotorYear, string MakeStr, string ModelStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getChromeMenuCache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getChromeMenuCache(string SessionID, int Operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getChromeMenuCache", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getChromeMenuCacheAsync(string SessionID, int Operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getChromeStyleIDByVIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getChromeStyleIDByVIN(string SessionID, int Operation, string Vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getChromeStyleIDByVIN", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getChromeStyleIDByVINAsync(string SessionID, int Operation, string Vin);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getBlackbookMenuCache", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getBlackbookMenuCache(string SessionID, int Operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getBlackbookMenuCache", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getBlackbookMenuCacheAsync(string SessionID, int Operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetDASChromeModels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetDASChromeModels(string SessionID, int Operation, string MotorYear, string Make);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetDASChromeModels", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetDASChromeModelsAsync(string SessionID, int Operation, string MotorYear, string Make);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DAS_Get_Motor_Years", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue DAS_Get_Motor_Years(string SessionID, int Operation, string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DAS_Get_Motor_Years", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DAS_Get_Motor_YearsAsync(string SessionID, int Operation, string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DAS_Get_Motor_Makes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue DAS_Get_Motor_Makes(string SessionID, int Operation, string MotorYear, string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DAS_Get_Motor_Makes", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DAS_Get_Motor_MakesAsync(string SessionID, int Operation, string MotorYear, string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DAS_Get_Motor_Models", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue DAS_Get_Motor_Models(string SessionID, int Operation, string MotorYear, string Make, string Source, string CurrentModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DAS_Get_Motor_Models", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DAS_Get_Motor_ModelsAsync(string SessionID, int Operation, string MotorYear, string Make, string Source, string CurrentModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DAS_Get_Motor_Styles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue DAS_Get_Motor_Styles(string SessionID, int Operation, string MotorYear, string Make, string Model, string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DAS_Get_Motor_Styles", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DAS_Get_Motor_StylesAsync(string SessionID, int Operation, string MotorYear, string Make, string Model, string Source);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DealerImport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue DealerImport(string SessionID, int Operation, string Dealer, string VehicleInvAcc, string DealerFilePath, string FilePath, string Delimiter, int kDealerImport, int ImportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/DealerImport", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DealerImportAsync(string SessionID, int Operation, string Dealer, string VehicleInvAcc, string DealerFilePath, string FilePath, string Delimiter, int kDealerImport, int ImportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/importStatusGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue importStatusGet(string SessionID, int Operation, string Dealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/importStatusGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> importStatusGetAsync(string SessionID, int Operation, string Dealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/setDetailsDone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue setDetailsDone(string SessionID, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/setDetailsDone", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> setDetailsDoneAsync(string SessionID, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetEbay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetEbay(string SessionID, string Listing, int FilterType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetEbay", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetEbayAsync(string SessionID, string Listing, int FilterType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getWebAd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getWebAd(string SessionID, string Listing, int FilterType, int Auction);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getWebAd", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getWebAdAsync(string SessionID, string Listing, int FilterType, int Auction);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getEbayDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getEbayDetails(string SessionID, string Listing, int FilterType, int iCertified, int iStyleSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getEbayDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getEbayDetailsAsync(string SessionID, string Listing, int FilterType, int iCertified, int iStyleSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getWebAdDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getWebAdDetails(string SessionID, string Listing, int Distance, int Certified, int StyleSearch, int Auction, int FilterType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getWebAdDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getWebAdDetailsAsync(string SessionID, string Listing, int Distance, int Certified, int StyleSearch, int Auction, int FilterType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getBlackbookAdjustments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getBlackbookAdjustments(string SessionID, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getBlackbookAdjustments", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getBlackbookAdjustmentsAsync(string SessionID, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getFilters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getFilters(string SessionID, int Dealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getFilters", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getFiltersAsync(string SessionID, int Dealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GenerateWindowSticker", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GenerateWindowSticker(string SessionID, int kListing, int kTemplate, int UsebackgroundImage, double Price, int PrintQRCode, int PrintBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GenerateWindowSticker", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GenerateWindowStickerAsync(string SessionID, int kListing, int kTemplate, int UsebackgroundImage, double Price, int PrintQRCode, int PrintBarCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GenerateBuyersGuide", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GenerateBuyersGuide(
                    string SessionID, 
                    int kListing, 
                    int kTemplate, 
                    int iWarrantyType, 
                    int iLaborCoverage, 
                    int iPartsCoverage, 
                    string SystemsCovered, 
                    string WarrantyDuration, 
                    int iServiceContract, 
                    string Complaints, 
                    int UseBackgroundImage, 
                    int Print2ndPage, 
                    int PrintQRCode, 
                    int PrintBarCodeint, 
                    int ManWarrantyApplies, 
                    int ManUsedWarrantyApplies, 
                    int OtherUsedWarrantyApplies, 
                    int PriorRental, 
                    int HasWarranty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GenerateBuyersGuide", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GenerateBuyersGuideAsync(
                    string SessionID, 
                    int kListing, 
                    int kTemplate, 
                    int iWarrantyType, 
                    int iLaborCoverage, 
                    int iPartsCoverage, 
                    string SystemsCovered, 
                    string WarrantyDuration, 
                    int iServiceContract, 
                    string Complaints, 
                    int UseBackgroundImage, 
                    int Print2ndPage, 
                    int PrintQRCode, 
                    int PrintBarCodeint, 
                    int ManWarrantyApplies, 
                    int ManUsedWarrantyApplies, 
                    int OtherUsedWarrantyApplies, 
                    int PriorRental, 
                    int HasWarranty);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/FetchBuyersGuideWindowStickers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue FetchBuyersGuideWindowStickers(string SessionID, int kDealer, int kListing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/FetchBuyersGuideWindowStickers", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> FetchBuyersGuideWindowStickersAsync(string SessionID, int kDealer, int kListing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetVinExplosion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetVinExplosion(string SessionID, string VIN, string StyleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetVinExplosion", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetVinExplosionAsync(string SessionID, string VIN, string StyleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetNewVIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetNewVIN(string SessionID, string Listing, string VIN, int DrillDown);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetNewVIN", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetNewVINAsync(string SessionID, string Listing, string VIN, int DrillDown);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetNewStyleID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetNewStyleID(string SessionID, string Listing, string VIN, string Year, string Make, string Model, string Style, string StyleID, int DrillDown);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetNewStyleID", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetNewStyleIDAsync(string SessionID, string Listing, string VIN, string Year, string Make, string Model, string Style, string StyleID, int DrillDown);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/dealerAnalytics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue dealerAnalytics(string SessionID, int Dealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/dealerAnalytics", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> dealerAnalyticsAsync(string SessionID, int Dealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/dealerPricing", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue dealerPricing(string SessionID, int Dealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/dealerPricing", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> dealerPricingAsync(string SessionID, int Dealer);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetWebAdDetailsPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue GetWebAdDetailsPhoto(string SessionID, int Listing, int WebAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetWebAdDetailsPhoto", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetWebAdDetailsPhotoAsync(string SessionID, int Listing, int WebAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/resolveBlackbook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue resolveBlackbook(string SessionID, int Operation, string Listing, string Mode, string Blackbook, string MotorYear, string Make, string Model, string Series, string Style);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/resolveBlackbook", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> resolveBlackbookAsync(string SessionID, int Operation, string Listing, string Mode, string Blackbook, string MotorYear, string Make, string Model, string Series, string Style);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/resolveBluebook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue resolveBluebook(string SessionID, int Operation, string Listing, string VehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/resolveBluebook", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> resolveBluebookAsync(string SessionID, int Operation, string Listing, string VehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getBluebookOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue getBluebookOptions(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/getBluebookOptions", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getBluebookOptionsAsync(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/BookOptionsSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue BookOptionsSet(string SessionID, int Operation, string Listing, int Condition, string AdjCode, int KBBCondition, string KBBOptionIds, int iBBBook, int iKBBBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/BookOptionsSet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> BookOptionsSetAsync(string SessionID, int Operation, string Listing, int Condition, string AdjCode, int KBBCondition, string KBBOptionIds, int iBBBook, int iKBBBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/bluebookBaseGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue bluebookBaseGet(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/bluebookBaseGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> bluebookBaseGetAsync(string SessionID, int Operation, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/blackbookBaseGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue blackbookBaseGet(string SessionID, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/blackbookBaseGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> blackbookBaseGetAsync(string SessionID, string Listing);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/BulkPrintWS_BG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue BulkPrintWS_BG(string SessionID, int Dealer, System.Data.DataSet BulkPrint, int WindowStickerTemplate, int BuyersGuideTemplate, int PriceType, int ServiceContract, int ManWarrantyApplies, int ManUsedWarrantyApplies, int OtherUsedWarrantyApplies, int PriorRental);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/BulkPrintWS_BG", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> BulkPrintWS_BGAsync(string SessionID, int Dealer, System.Data.DataSet BulkPrint, int WindowStickerTemplate, int BuyersGuideTemplate, int PriceType, int ServiceContract, int ManWarrantyApplies, int ManUsedWarrantyApplies, int OtherUsedWarrantyApplies, int PriorRental);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetVehicleReserved", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetVehicleReserved(string SessionID, System.Data.DataSet dsReservedVehicle);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetVehicleReserved", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetVehicleReservedAsync(string SessionID, System.Data.DataSet dsReservedVehicle);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetVehicleSold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.OldDAS.lmReturnValue SetVehicleSold(string SessionID, int kDealer, int kPerson, int kGroundingDealer, int kListing, int SalePrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/SetVehicleSold", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetVehicleSoldAsync(string SessionID, int kDealer, int kPerson, int kGroundingDealer, int kListing, int SalePrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetLastError", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLastError(string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://protal.liquidmotors.com/GetLastError", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetLastErrorAsync(string SessionID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://protal.liquidmotors.com")]
    public partial class lmReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReturnCodes resultField;
        
        private string resultStringField;
        
        private System.Data.DataSet dsField;
        
        private System.Data.DataSet performanceDSField;
        
        private bool dSIsValidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReturnCodes Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultString {
            get {
                return this.resultStringField;
            }
            set {
                this.resultStringField = value;
                this.RaisePropertyChanged("ResultString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataSet DS {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
                this.RaisePropertyChanged("DS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Data.DataSet PerformanceDS {
            get {
                return this.performanceDSField;
            }
            set {
                this.performanceDSField = value;
                this.RaisePropertyChanged("PerformanceDS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool DSIsValid {
            get {
                return this.dSIsValidField;
            }
            set {
                this.dSIsValidField = value;
                this.RaisePropertyChanged("DSIsValid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://protal.liquidmotors.com")]
    public enum ReturnCodes {
        
        /// <remarks/>
        LM_GENERICERROR,
        
        /// <remarks/>
        LM_MISSINGASSOCIATIONS,
        
        /// <remarks/>
        LM_DBERROR,
        
        /// <remarks/>
        LM_RELAYCOMMERROR,
        
        /// <remarks/>
        LM_INVALIDSESSION,
        
        /// <remarks/>
        LM_SUCCESS,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DASSoapChannel : LMWholesale.OldDAS.DASSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DASSoapClient : System.ServiceModel.ClientBase<LMWholesale.OldDAS.DASSoap>, LMWholesale.OldDAS.DASSoap {
        
        public DASSoapClient() {
        }
        
        public DASSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DASSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DASSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DASSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetAnalytics(string SessionID, int DealerGroup, int DealerID, string Listing, int StockType, int Status, int IconStatus, int PrintStatus) {
            return base.Channel.GetAnalytics(SessionID, DealerGroup, DealerID, Listing, StockType, Status, IconStatus, PrintStatus);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsAsync(string SessionID, int DealerGroup, int DealerID, string Listing, int StockType, int Status, int IconStatus, int PrintStatus) {
            return base.Channel.GetAnalyticsAsync(SessionID, DealerGroup, DealerID, Listing, StockType, Status, IconStatus, PrintStatus);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetAnalyticsReRun(string SessionID, int Operation, string Listing) {
            return base.Channel.GetAnalyticsReRun(SessionID, Operation, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsReRunAsync(string SessionID, int Operation, string Listing) {
            return base.Channel.GetAnalyticsReRunAsync(SessionID, Operation, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetAnalyticsDetailed(string SessionID, string Listing, int Distance, int Certified, int StyleSearch, string Auction, int FilterType) {
            return base.Channel.GetAnalyticsDetailed(SessionID, Listing, Distance, Certified, StyleSearch, Auction, FilterType);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsDetailedAsync(string SessionID, string Listing, int Distance, int Certified, int StyleSearch, string Auction, int FilterType) {
            return base.Channel.GetAnalyticsDetailedAsync(SessionID, Listing, Distance, Certified, StyleSearch, Auction, FilterType);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetAnalyticsELink(string SessionID, int Operation, string Listing) {
            return base.Channel.GetAnalyticsELink(SessionID, Operation, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsELinkAsync(string SessionID, int Operation, string Listing) {
            return base.Channel.GetAnalyticsELinkAsync(SessionID, Operation, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetAnalyticsFeatures(string SessionID, int Operation, string Year, string Make, string Model, string Series, string Style) {
            return base.Channel.GetAnalyticsFeatures(SessionID, Operation, Year, Make, Model, Series, Style);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsFeaturesAsync(string SessionID, int Operation, string Year, string Make, string Model, string Series, string Style) {
            return base.Channel.GetAnalyticsFeaturesAsync(SessionID, Operation, Year, Make, Model, Series, Style);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetAnalyticsDefine(string SessionID, int Operation, string Listing, int Mode, int Item, string Feature) {
            return base.Channel.SetAnalyticsDefine(SessionID, Operation, Listing, Mode, Item, Feature);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsDefineAsync(string SessionID, int Operation, string Listing, int Mode, int Item, string Feature) {
            return base.Channel.SetAnalyticsDefineAsync(SessionID, Operation, Listing, Mode, Item, Feature);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetAnalyticsOptions(string SessionID, int Operation, string Listing) {
            return base.Channel.GetAnalyticsOptions(SessionID, Operation, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsOptionsAsync(string SessionID, int Operation, string Listing) {
            return base.Channel.GetAnalyticsOptionsAsync(SessionID, Operation, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetAnalyticsUpdate(string SessionID, int Operation, string Listing, string StockNumber, string Miles, string Cost, string ListPrice, int ImportOverride, string InternetPrice) {
            return base.Channel.SetAnalyticsUpdate(SessionID, Operation, Listing, StockNumber, Miles, Cost, ListPrice, ImportOverride, InternetPrice);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsUpdateAsync(string SessionID, int Operation, string Listing, string StockNumber, string Miles, string Cost, string ListPrice, int ImportOverride, string InternetPrice) {
            return base.Channel.SetAnalyticsUpdateAsync(SessionID, Operation, Listing, StockNumber, Miles, Cost, ListPrice, ImportOverride, InternetPrice);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetAnalyticsDASInventory(
                    string SessionID, 
                    int Operation, 
                    int Dealer, 
                    string StockNumber, 
                    string VIN, 
                    string MotorYear, 
                    int Miles, 
                    int InvCost, 
                    int ListPrice, 
                    string MakeStr, 
                    string ModelStr, 
                    string StyleStr, 
                    string StyleID, 
                    string sMode, 
                    int DrillDown, 
                    int StockType, 
                    int Status, 
                    int ImportOverride, 
                    int InternetPrice, 
                    int kVehicleClass) {
            return base.Channel.SetAnalyticsDASInventory(SessionID, Operation, Dealer, StockNumber, VIN, MotorYear, Miles, InvCost, ListPrice, MakeStr, ModelStr, StyleStr, StyleID, sMode, DrillDown, StockType, Status, ImportOverride, InternetPrice, kVehicleClass);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsDASInventoryAsync(
                    string SessionID, 
                    int Operation, 
                    int Dealer, 
                    string StockNumber, 
                    string VIN, 
                    string MotorYear, 
                    int Miles, 
                    int InvCost, 
                    int ListPrice, 
                    string MakeStr, 
                    string ModelStr, 
                    string StyleStr, 
                    string StyleID, 
                    string sMode, 
                    int DrillDown, 
                    int StockType, 
                    int Status, 
                    int ImportOverride, 
                    int InternetPrice, 
                    int kVehicleClass) {
            return base.Channel.SetAnalyticsDASInventoryAsync(SessionID, Operation, Dealer, StockNumber, VIN, MotorYear, Miles, InvCost, ListPrice, MakeStr, ModelStr, StyleStr, StyleID, sMode, DrillDown, StockType, Status, ImportOverride, InternetPrice, kVehicleClass);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetAnalyticsCommit(string SessionID, int Operation, string Listing, string StockNumber) {
            return base.Channel.SetAnalyticsCommit(SessionID, Operation, Listing, StockNumber);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsCommitAsync(string SessionID, int Operation, string Listing, string StockNumber) {
            return base.Channel.SetAnalyticsCommitAsync(SessionID, Operation, Listing, StockNumber);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetAnalyticsDelete(string SessionID, int Operation, string Listing) {
            return base.Channel.SetAnalyticsDelete(SessionID, Operation, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetAnalyticsDeleteAsync(string SessionID, int Operation, string Listing) {
            return base.Channel.SetAnalyticsDeleteAsync(SessionID, Operation, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetAnalyticsInfo(string SessionID, int Operation, string VIN) {
            return base.Channel.GetAnalyticsInfo(SessionID, Operation, VIN);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetAnalyticsInfoAsync(string SessionID, int Operation, string VIN) {
            return base.Channel.GetAnalyticsInfoAsync(SessionID, Operation, VIN);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetBBValues(string SessionID, int Operation, string VIN, string Listing) {
            return base.Channel.GetBBValues(SessionID, Operation, VIN, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetBBValuesAsync(string SessionID, int Operation, string VIN, string Listing) {
            return base.Channel.GetBBValuesAsync(SessionID, Operation, VIN, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetUpdateInventory(
                    string SessionID, 
                    string Listing, 
                    string StockNumber, 
                    string VIN, 
                    string Miles, 
                    string InvCost, 
                    string ListPrice, 
                    string Year, 
                    string Make, 
                    string Model, 
                    string Style, 
                    string StyleID, 
                    string Mode, 
                    int DrillDown, 
                    int StockType, 
                    int Status, 
                    int ImportOverride) {
            return base.Channel.SetUpdateInventory(SessionID, Listing, StockNumber, VIN, Miles, InvCost, ListPrice, Year, Make, Model, Style, StyleID, Mode, DrillDown, StockType, Status, ImportOverride);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetUpdateInventoryAsync(
                    string SessionID, 
                    string Listing, 
                    string StockNumber, 
                    string VIN, 
                    string Miles, 
                    string InvCost, 
                    string ListPrice, 
                    string Year, 
                    string Make, 
                    string Model, 
                    string Style, 
                    string StyleID, 
                    string Mode, 
                    int DrillDown, 
                    int StockType, 
                    int Status, 
                    int ImportOverride) {
            return base.Channel.SetUpdateInventoryAsync(SessionID, Listing, StockNumber, VIN, Miles, InvCost, ListPrice, Year, Make, Model, Style, StyleID, Mode, DrillDown, StockType, Status, ImportOverride);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetDASChromeYear(string SessionID, int Operation, string MotorYear) {
            return base.Channel.GetDASChromeYear(SessionID, Operation, MotorYear);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetDASChromeYearAsync(string SessionID, int Operation, string MotorYear) {
            return base.Channel.GetDASChromeYearAsync(SessionID, Operation, MotorYear);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetDASChromeStyles(string SessionID, int Operation, string Vin, string MotorYear, string MakeStr, string ModelStr) {
            return base.Channel.GetDASChromeStyles(SessionID, Operation, Vin, MotorYear, MakeStr, ModelStr);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetDASChromeStylesAsync(string SessionID, int Operation, string Vin, string MotorYear, string MakeStr, string ModelStr) {
            return base.Channel.GetDASChromeStylesAsync(SessionID, Operation, Vin, MotorYear, MakeStr, ModelStr);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getChromeMenuCache(string SessionID, int Operation) {
            return base.Channel.getChromeMenuCache(SessionID, Operation);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getChromeMenuCacheAsync(string SessionID, int Operation) {
            return base.Channel.getChromeMenuCacheAsync(SessionID, Operation);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getChromeStyleIDByVIN(string SessionID, int Operation, string Vin) {
            return base.Channel.getChromeStyleIDByVIN(SessionID, Operation, Vin);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getChromeStyleIDByVINAsync(string SessionID, int Operation, string Vin) {
            return base.Channel.getChromeStyleIDByVINAsync(SessionID, Operation, Vin);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getBlackbookMenuCache(string SessionID, int Operation) {
            return base.Channel.getBlackbookMenuCache(SessionID, Operation);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getBlackbookMenuCacheAsync(string SessionID, int Operation) {
            return base.Channel.getBlackbookMenuCacheAsync(SessionID, Operation);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetDASChromeModels(string SessionID, int Operation, string MotorYear, string Make) {
            return base.Channel.GetDASChromeModels(SessionID, Operation, MotorYear, Make);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetDASChromeModelsAsync(string SessionID, int Operation, string MotorYear, string Make) {
            return base.Channel.GetDASChromeModelsAsync(SessionID, Operation, MotorYear, Make);
        }
        
        public LMWholesale.OldDAS.lmReturnValue DAS_Get_Motor_Years(string SessionID, int Operation, string Source) {
            return base.Channel.DAS_Get_Motor_Years(SessionID, Operation, Source);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DAS_Get_Motor_YearsAsync(string SessionID, int Operation, string Source) {
            return base.Channel.DAS_Get_Motor_YearsAsync(SessionID, Operation, Source);
        }
        
        public LMWholesale.OldDAS.lmReturnValue DAS_Get_Motor_Makes(string SessionID, int Operation, string MotorYear, string Source) {
            return base.Channel.DAS_Get_Motor_Makes(SessionID, Operation, MotorYear, Source);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DAS_Get_Motor_MakesAsync(string SessionID, int Operation, string MotorYear, string Source) {
            return base.Channel.DAS_Get_Motor_MakesAsync(SessionID, Operation, MotorYear, Source);
        }
        
        public LMWholesale.OldDAS.lmReturnValue DAS_Get_Motor_Models(string SessionID, int Operation, string MotorYear, string Make, string Source, string CurrentModel) {
            return base.Channel.DAS_Get_Motor_Models(SessionID, Operation, MotorYear, Make, Source, CurrentModel);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DAS_Get_Motor_ModelsAsync(string SessionID, int Operation, string MotorYear, string Make, string Source, string CurrentModel) {
            return base.Channel.DAS_Get_Motor_ModelsAsync(SessionID, Operation, MotorYear, Make, Source, CurrentModel);
        }
        
        public LMWholesale.OldDAS.lmReturnValue DAS_Get_Motor_Styles(string SessionID, int Operation, string MotorYear, string Make, string Model, string Source) {
            return base.Channel.DAS_Get_Motor_Styles(SessionID, Operation, MotorYear, Make, Model, Source);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DAS_Get_Motor_StylesAsync(string SessionID, int Operation, string MotorYear, string Make, string Model, string Source) {
            return base.Channel.DAS_Get_Motor_StylesAsync(SessionID, Operation, MotorYear, Make, Model, Source);
        }
        
        public LMWholesale.OldDAS.lmReturnValue DealerImport(string SessionID, int Operation, string Dealer, string VehicleInvAcc, string DealerFilePath, string FilePath, string Delimiter, int kDealerImport, int ImportType) {
            return base.Channel.DealerImport(SessionID, Operation, Dealer, VehicleInvAcc, DealerFilePath, FilePath, Delimiter, kDealerImport, ImportType);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> DealerImportAsync(string SessionID, int Operation, string Dealer, string VehicleInvAcc, string DealerFilePath, string FilePath, string Delimiter, int kDealerImport, int ImportType) {
            return base.Channel.DealerImportAsync(SessionID, Operation, Dealer, VehicleInvAcc, DealerFilePath, FilePath, Delimiter, kDealerImport, ImportType);
        }
        
        public LMWholesale.OldDAS.lmReturnValue importStatusGet(string SessionID, int Operation, string Dealer) {
            return base.Channel.importStatusGet(SessionID, Operation, Dealer);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> importStatusGetAsync(string SessionID, int Operation, string Dealer) {
            return base.Channel.importStatusGetAsync(SessionID, Operation, Dealer);
        }
        
        public LMWholesale.OldDAS.lmReturnValue setDetailsDone(string SessionID, string Listing) {
            return base.Channel.setDetailsDone(SessionID, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> setDetailsDoneAsync(string SessionID, string Listing) {
            return base.Channel.setDetailsDoneAsync(SessionID, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetEbay(string SessionID, string Listing, int FilterType) {
            return base.Channel.GetEbay(SessionID, Listing, FilterType);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetEbayAsync(string SessionID, string Listing, int FilterType) {
            return base.Channel.GetEbayAsync(SessionID, Listing, FilterType);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getWebAd(string SessionID, string Listing, int FilterType, int Auction) {
            return base.Channel.getWebAd(SessionID, Listing, FilterType, Auction);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getWebAdAsync(string SessionID, string Listing, int FilterType, int Auction) {
            return base.Channel.getWebAdAsync(SessionID, Listing, FilterType, Auction);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getEbayDetails(string SessionID, string Listing, int FilterType, int iCertified, int iStyleSearch) {
            return base.Channel.getEbayDetails(SessionID, Listing, FilterType, iCertified, iStyleSearch);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getEbayDetailsAsync(string SessionID, string Listing, int FilterType, int iCertified, int iStyleSearch) {
            return base.Channel.getEbayDetailsAsync(SessionID, Listing, FilterType, iCertified, iStyleSearch);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getWebAdDetails(string SessionID, string Listing, int Distance, int Certified, int StyleSearch, int Auction, int FilterType) {
            return base.Channel.getWebAdDetails(SessionID, Listing, Distance, Certified, StyleSearch, Auction, FilterType);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getWebAdDetailsAsync(string SessionID, string Listing, int Distance, int Certified, int StyleSearch, int Auction, int FilterType) {
            return base.Channel.getWebAdDetailsAsync(SessionID, Listing, Distance, Certified, StyleSearch, Auction, FilterType);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getBlackbookAdjustments(string SessionID, string Listing) {
            return base.Channel.getBlackbookAdjustments(SessionID, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getBlackbookAdjustmentsAsync(string SessionID, string Listing) {
            return base.Channel.getBlackbookAdjustmentsAsync(SessionID, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getFilters(string SessionID, int Dealer) {
            return base.Channel.getFilters(SessionID, Dealer);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getFiltersAsync(string SessionID, int Dealer) {
            return base.Channel.getFiltersAsync(SessionID, Dealer);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GenerateWindowSticker(string SessionID, int kListing, int kTemplate, int UsebackgroundImage, double Price, int PrintQRCode, int PrintBarCode) {
            return base.Channel.GenerateWindowSticker(SessionID, kListing, kTemplate, UsebackgroundImage, Price, PrintQRCode, PrintBarCode);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GenerateWindowStickerAsync(string SessionID, int kListing, int kTemplate, int UsebackgroundImage, double Price, int PrintQRCode, int PrintBarCode) {
            return base.Channel.GenerateWindowStickerAsync(SessionID, kListing, kTemplate, UsebackgroundImage, Price, PrintQRCode, PrintBarCode);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GenerateBuyersGuide(
                    string SessionID, 
                    int kListing, 
                    int kTemplate, 
                    int iWarrantyType, 
                    int iLaborCoverage, 
                    int iPartsCoverage, 
                    string SystemsCovered, 
                    string WarrantyDuration, 
                    int iServiceContract, 
                    string Complaints, 
                    int UseBackgroundImage, 
                    int Print2ndPage, 
                    int PrintQRCode, 
                    int PrintBarCodeint, 
                    int ManWarrantyApplies, 
                    int ManUsedWarrantyApplies, 
                    int OtherUsedWarrantyApplies, 
                    int PriorRental, 
                    int HasWarranty) {
            return base.Channel.GenerateBuyersGuide(SessionID, kListing, kTemplate, iWarrantyType, iLaborCoverage, iPartsCoverage, SystemsCovered, WarrantyDuration, iServiceContract, Complaints, UseBackgroundImage, Print2ndPage, PrintQRCode, PrintBarCodeint, ManWarrantyApplies, ManUsedWarrantyApplies, OtherUsedWarrantyApplies, PriorRental, HasWarranty);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GenerateBuyersGuideAsync(
                    string SessionID, 
                    int kListing, 
                    int kTemplate, 
                    int iWarrantyType, 
                    int iLaborCoverage, 
                    int iPartsCoverage, 
                    string SystemsCovered, 
                    string WarrantyDuration, 
                    int iServiceContract, 
                    string Complaints, 
                    int UseBackgroundImage, 
                    int Print2ndPage, 
                    int PrintQRCode, 
                    int PrintBarCodeint, 
                    int ManWarrantyApplies, 
                    int ManUsedWarrantyApplies, 
                    int OtherUsedWarrantyApplies, 
                    int PriorRental, 
                    int HasWarranty) {
            return base.Channel.GenerateBuyersGuideAsync(SessionID, kListing, kTemplate, iWarrantyType, iLaborCoverage, iPartsCoverage, SystemsCovered, WarrantyDuration, iServiceContract, Complaints, UseBackgroundImage, Print2ndPage, PrintQRCode, PrintBarCodeint, ManWarrantyApplies, ManUsedWarrantyApplies, OtherUsedWarrantyApplies, PriorRental, HasWarranty);
        }
        
        public LMWholesale.OldDAS.lmReturnValue FetchBuyersGuideWindowStickers(string SessionID, int kDealer, int kListing) {
            return base.Channel.FetchBuyersGuideWindowStickers(SessionID, kDealer, kListing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> FetchBuyersGuideWindowStickersAsync(string SessionID, int kDealer, int kListing) {
            return base.Channel.FetchBuyersGuideWindowStickersAsync(SessionID, kDealer, kListing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetVinExplosion(string SessionID, string VIN, string StyleID) {
            return base.Channel.GetVinExplosion(SessionID, VIN, StyleID);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetVinExplosionAsync(string SessionID, string VIN, string StyleID) {
            return base.Channel.GetVinExplosionAsync(SessionID, VIN, StyleID);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetNewVIN(string SessionID, string Listing, string VIN, int DrillDown) {
            return base.Channel.SetNewVIN(SessionID, Listing, VIN, DrillDown);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetNewVINAsync(string SessionID, string Listing, string VIN, int DrillDown) {
            return base.Channel.SetNewVINAsync(SessionID, Listing, VIN, DrillDown);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetNewStyleID(string SessionID, string Listing, string VIN, string Year, string Make, string Model, string Style, string StyleID, int DrillDown) {
            return base.Channel.SetNewStyleID(SessionID, Listing, VIN, Year, Make, Model, Style, StyleID, DrillDown);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetNewStyleIDAsync(string SessionID, string Listing, string VIN, string Year, string Make, string Model, string Style, string StyleID, int DrillDown) {
            return base.Channel.SetNewStyleIDAsync(SessionID, Listing, VIN, Year, Make, Model, Style, StyleID, DrillDown);
        }
        
        public LMWholesale.OldDAS.lmReturnValue dealerAnalytics(string SessionID, int Dealer) {
            return base.Channel.dealerAnalytics(SessionID, Dealer);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> dealerAnalyticsAsync(string SessionID, int Dealer) {
            return base.Channel.dealerAnalyticsAsync(SessionID, Dealer);
        }
        
        public LMWholesale.OldDAS.lmReturnValue dealerPricing(string SessionID, int Dealer) {
            return base.Channel.dealerPricing(SessionID, Dealer);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> dealerPricingAsync(string SessionID, int Dealer) {
            return base.Channel.dealerPricingAsync(SessionID, Dealer);
        }
        
        public LMWholesale.OldDAS.lmReturnValue GetWebAdDetailsPhoto(string SessionID, int Listing, int WebAd) {
            return base.Channel.GetWebAdDetailsPhoto(SessionID, Listing, WebAd);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> GetWebAdDetailsPhotoAsync(string SessionID, int Listing, int WebAd) {
            return base.Channel.GetWebAdDetailsPhotoAsync(SessionID, Listing, WebAd);
        }
        
        public LMWholesale.OldDAS.lmReturnValue resolveBlackbook(string SessionID, int Operation, string Listing, string Mode, string Blackbook, string MotorYear, string Make, string Model, string Series, string Style) {
            return base.Channel.resolveBlackbook(SessionID, Operation, Listing, Mode, Blackbook, MotorYear, Make, Model, Series, Style);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> resolveBlackbookAsync(string SessionID, int Operation, string Listing, string Mode, string Blackbook, string MotorYear, string Make, string Model, string Series, string Style) {
            return base.Channel.resolveBlackbookAsync(SessionID, Operation, Listing, Mode, Blackbook, MotorYear, Make, Model, Series, Style);
        }
        
        public LMWholesale.OldDAS.lmReturnValue resolveBluebook(string SessionID, int Operation, string Listing, string VehicleId) {
            return base.Channel.resolveBluebook(SessionID, Operation, Listing, VehicleId);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> resolveBluebookAsync(string SessionID, int Operation, string Listing, string VehicleId) {
            return base.Channel.resolveBluebookAsync(SessionID, Operation, Listing, VehicleId);
        }
        
        public LMWholesale.OldDAS.lmReturnValue getBluebookOptions(string SessionID, int Operation, string Listing) {
            return base.Channel.getBluebookOptions(SessionID, Operation, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> getBluebookOptionsAsync(string SessionID, int Operation, string Listing) {
            return base.Channel.getBluebookOptionsAsync(SessionID, Operation, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue BookOptionsSet(string SessionID, int Operation, string Listing, int Condition, string AdjCode, int KBBCondition, string KBBOptionIds, int iBBBook, int iKBBBook) {
            return base.Channel.BookOptionsSet(SessionID, Operation, Listing, Condition, AdjCode, KBBCondition, KBBOptionIds, iBBBook, iKBBBook);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> BookOptionsSetAsync(string SessionID, int Operation, string Listing, int Condition, string AdjCode, int KBBCondition, string KBBOptionIds, int iBBBook, int iKBBBook) {
            return base.Channel.BookOptionsSetAsync(SessionID, Operation, Listing, Condition, AdjCode, KBBCondition, KBBOptionIds, iBBBook, iKBBBook);
        }
        
        public LMWholesale.OldDAS.lmReturnValue bluebookBaseGet(string SessionID, int Operation, string Listing) {
            return base.Channel.bluebookBaseGet(SessionID, Operation, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> bluebookBaseGetAsync(string SessionID, int Operation, string Listing) {
            return base.Channel.bluebookBaseGetAsync(SessionID, Operation, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue blackbookBaseGet(string SessionID, string Listing) {
            return base.Channel.blackbookBaseGet(SessionID, Listing);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> blackbookBaseGetAsync(string SessionID, string Listing) {
            return base.Channel.blackbookBaseGetAsync(SessionID, Listing);
        }
        
        public LMWholesale.OldDAS.lmReturnValue BulkPrintWS_BG(string SessionID, int Dealer, System.Data.DataSet BulkPrint, int WindowStickerTemplate, int BuyersGuideTemplate, int PriceType, int ServiceContract, int ManWarrantyApplies, int ManUsedWarrantyApplies, int OtherUsedWarrantyApplies, int PriorRental) {
            return base.Channel.BulkPrintWS_BG(SessionID, Dealer, BulkPrint, WindowStickerTemplate, BuyersGuideTemplate, PriceType, ServiceContract, ManWarrantyApplies, ManUsedWarrantyApplies, OtherUsedWarrantyApplies, PriorRental);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> BulkPrintWS_BGAsync(string SessionID, int Dealer, System.Data.DataSet BulkPrint, int WindowStickerTemplate, int BuyersGuideTemplate, int PriceType, int ServiceContract, int ManWarrantyApplies, int ManUsedWarrantyApplies, int OtherUsedWarrantyApplies, int PriorRental) {
            return base.Channel.BulkPrintWS_BGAsync(SessionID, Dealer, BulkPrint, WindowStickerTemplate, BuyersGuideTemplate, PriceType, ServiceContract, ManWarrantyApplies, ManUsedWarrantyApplies, OtherUsedWarrantyApplies, PriorRental);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetVehicleReserved(string SessionID, System.Data.DataSet dsReservedVehicle) {
            return base.Channel.SetVehicleReserved(SessionID, dsReservedVehicle);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetVehicleReservedAsync(string SessionID, System.Data.DataSet dsReservedVehicle) {
            return base.Channel.SetVehicleReservedAsync(SessionID, dsReservedVehicle);
        }
        
        public LMWholesale.OldDAS.lmReturnValue SetVehicleSold(string SessionID, int kDealer, int kPerson, int kGroundingDealer, int kListing, int SalePrice) {
            return base.Channel.SetVehicleSold(SessionID, kDealer, kPerson, kGroundingDealer, kListing, SalePrice);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.OldDAS.lmReturnValue> SetVehicleSoldAsync(string SessionID, int kDealer, int kPerson, int kGroundingDealer, int kListing, int SalePrice) {
            return base.Channel.SetVehicleSoldAsync(SessionID, kDealer, kPerson, kGroundingDealer, kListing, SalePrice);
        }
        
        public string GetLastError(string SessionID) {
            return base.Channel.GetLastError(SessionID);
        }
        
        public System.Threading.Tasks.Task<string> GetLastErrorAsync(string SessionID) {
            return base.Channel.GetLastErrorAsync(SessionID);
        }
    }
}
