//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMWholesale.Dealer {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.liquidmotors.com", ConfigurationName="Dealer.DealerSoap")]
    public interface DealerSoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetDealerInfoRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetDealerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.GetDealerInfoResponse GetDealerInfo(LMWholesale.Dealer.GetDealerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetDealerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetDealerInfoResponse> GetDealerInfoAsync(LMWholesale.Dealer.GetDealerInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message LotLocationListGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/LotLocationListGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.LotLocationListGetResponse LotLocationListGet(LMWholesale.Dealer.LotLocationListGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/LotLocationListGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.LotLocationListGetResponse> LotLocationListGetAsync(LMWholesale.Dealer.LotLocationListGetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message ImportConfigGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/ImportConfigGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.ImportConfigGetResponse ImportConfigGet(LMWholesale.Dealer.ImportConfigGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/ImportConfigGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.ImportConfigGetResponse> ImportConfigGetAsync(LMWholesale.Dealer.ImportConfigGetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message ImportSystemGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/ImportSystemGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.ImportSystemGetResponse ImportSystemGet(LMWholesale.Dealer.ImportSystemGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/ImportSystemGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.ImportSystemGetResponse> ImportSystemGetAsync(LMWholesale.Dealer.ImportSystemGetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message DealerBaseSetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/DealerBaseSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.DealerBaseSetResponse DealerBaseSet(LMWholesale.Dealer.DealerBaseSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/DealerBaseSet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.DealerBaseSetResponse> DealerBaseSetAsync(LMWholesale.Dealer.DealerBaseSetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetDealerPathsRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetDealerPaths", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.GetDealerPathsResponse GetDealerPaths(LMWholesale.Dealer.GetDealerPathsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetDealerPaths", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetDealerPathsResponse> GetDealerPathsAsync(LMWholesale.Dealer.GetDealerPathsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetUserWidgetPreferencesRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetUserWidgetPreferences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.GetUserWidgetPreferencesResponse GetUserWidgetPreferences(LMWholesale.Dealer.GetUserWidgetPreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetUserWidgetPreferences", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetUserWidgetPreferencesResponse> GetUserWidgetPreferencesAsync(LMWholesale.Dealer.GetUserWidgetPreferencesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetDashInventoryHealthRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetDashInventoryHealth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.GetDashInventoryHealthResponse GetDashInventoryHealth(LMWholesale.Dealer.GetDashInventoryHealthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetDashInventoryHealth", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetDashInventoryHealthResponse> GetDashInventoryHealthAsync(LMWholesale.Dealer.GetDashInventoryHealthRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetImportHistoryDataRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetImportHistoryData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.GetImportHistoryDataResponse GetImportHistoryData(LMWholesale.Dealer.GetImportHistoryDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetImportHistoryData", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetImportHistoryDataResponse> GetImportHistoryDataAsync(LMWholesale.Dealer.GetImportHistoryDataRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message DealerNameCheckRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/DealerNameCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.DealerNameCheckResponse DealerNameCheck(LMWholesale.Dealer.DealerNameCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/DealerNameCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.DealerNameCheckResponse> DealerNameCheckAsync(LMWholesale.Dealer.DealerNameCheckRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetSignupPendingRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetSignupPending", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.GetSignupPendingResponse GetSignupPending(LMWholesale.Dealer.GetSignupPendingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetSignupPending", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetSignupPendingResponse> GetSignupPendingAsync(LMWholesale.Dealer.GetSignupPendingRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetSignupAuctionsRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetSignupAuctions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.GetSignupAuctionsResponse GetSignupAuctions(LMWholesale.Dealer.GetSignupAuctionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetSignupAuctions", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetSignupAuctionsResponse> GetSignupAuctionsAsync(LMWholesale.Dealer.GetSignupAuctionsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetPendingSetupRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetPendingSetup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.GetPendingSetupResponse GetPendingSetup(LMWholesale.Dealer.GetPendingSetupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetPendingSetup", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetPendingSetupResponse> GetPendingSetupAsync(LMWholesale.Dealer.GetPendingSetupRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message SetSignupRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/SetSignup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Dealer.SetSignupResponse SetSignup(LMWholesale.Dealer.SetSignupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/SetSignup", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Dealer.SetSignupResponse> SetSignupAsync(LMWholesale.Dealer.SetSignupRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class lmReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SerializableDictionary valuesField;
        
        private ReturnCode resultField;
        
        private string resultStringField;
        
        private System.Data.DataSet dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SerializableDictionary Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReturnCode Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResultString {
            get {
                return this.resultStringField;
            }
            set {
                this.resultStringField = value;
                this.RaisePropertyChanged("ResultString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Data.DataSet Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class SerializableDictionary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyValuePair[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public KeyValuePair[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class KeyValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public enum ReturnCode {
        
        /// <remarks/>
        LM_SUCCESS,
        
        /// <remarks/>
        LM_INVALIDSESSION,
        
        /// <remarks/>
        LM_RELAYCOMMERROR,
        
        /// <remarks/>
        LM_DBERROR,
        
        /// <remarks/>
        LM_MISSINGASSOCIATIONS,
        
        /// <remarks/>
        LM_GENERICERROR,
        
        /// <remarks/>
        LM_SECURITYERROR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDealerInfo", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetDealerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=2)]
        public string SingleTable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=3)]
        public string MultiTableName;
        
        public GetDealerInfoRequest() {
        }
        
        public GetDealerInfoRequest(string Session, int kDealer, string SingleTable, string MultiTableName) {
            this.Session = Session;
            this.kDealer = kDealer;
            this.SingleTable = SingleTable;
            this.MultiTableName = MultiTableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDealerInfoResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetDealerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue GetDealerInfoResult;
        
        public GetDealerInfoResponse() {
        }
        
        public GetDealerInfoResponse(LMWholesale.Dealer.lmReturnValue GetDealerInfoResult) {
            this.GetDealerInfoResult = GetDealerInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LotLocationListGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class LotLocationListGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        public LotLocationListGetRequest() {
        }
        
        public LotLocationListGetRequest(string Session, int kDealer) {
            this.Session = Session;
            this.kDealer = kDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LotLocationListGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class LotLocationListGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue LotLocationListGetResult;
        
        public LotLocationListGetResponse() {
        }
        
        public LotLocationListGetResponse(LMWholesale.Dealer.lmReturnValue LotLocationListGetResult) {
            this.LotLocationListGetResult = LotLocationListGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportConfigGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class ImportConfigGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        public ImportConfigGetRequest() {
        }
        
        public ImportConfigGetRequest(string Session, int kDealer) {
            this.Session = Session;
            this.kDealer = kDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportConfigGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class ImportConfigGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue ImportConfigGetResult;
        
        public ImportConfigGetResponse() {
        }
        
        public ImportConfigGetResponse(LMWholesale.Dealer.lmReturnValue ImportConfigGetResult) {
            this.ImportConfigGetResult = ImportConfigGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportSystemGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class ImportSystemGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public string VehicleInvAcc;
        
        public ImportSystemGetRequest() {
        }
        
        public ImportSystemGetRequest(string Session, string VehicleInvAcc) {
            this.Session = Session;
            this.VehicleInvAcc = VehicleInvAcc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportSystemGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class ImportSystemGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue ImportSystemGetResult;
        
        public ImportSystemGetResponse() {
        }
        
        public ImportSystemGetResponse(LMWholesale.Dealer.lmReturnValue ImportSystemGetResult) {
            this.ImportSystemGetResult = ImportSystemGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DealerBaseSet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class DealerBaseSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public string kDealer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=2)]
        public string jsonData;
        
        public DealerBaseSetRequest() {
        }
        
        public DealerBaseSetRequest(string Session, string kDealer, string jsonData) {
            this.Session = Session;
            this.kDealer = kDealer;
            this.jsonData = jsonData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DealerBaseSetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class DealerBaseSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue DealerBaseSetResult;
        
        public DealerBaseSetResponse() {
        }
        
        public DealerBaseSetResponse(LMWholesale.Dealer.lmReturnValue DealerBaseSetResult) {
            this.DealerBaseSetResult = DealerBaseSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDealerPaths", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetDealerPathsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        public GetDealerPathsRequest() {
        }
        
        public GetDealerPathsRequest(string Session, int kDealer) {
            this.Session = Session;
            this.kDealer = kDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDealerPathsResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetDealerPathsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue GetDealerPathsResult;
        
        public GetDealerPathsResponse() {
        }
        
        public GetDealerPathsResponse(LMWholesale.Dealer.lmReturnValue GetDealerPathsResult) {
            this.GetDealerPathsResult = GetDealerPathsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserWidgetPreferences", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetUserWidgetPreferencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=2)]
        public int kWidget;
        
        public GetUserWidgetPreferencesRequest() {
        }
        
        public GetUserWidgetPreferencesRequest(string Session, int kDealer, int kWidget) {
            this.Session = Session;
            this.kDealer = kDealer;
            this.kWidget = kWidget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserWidgetPreferencesResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetUserWidgetPreferencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue GetUserWidgetPreferencesResult;
        
        public GetUserWidgetPreferencesResponse() {
        }
        
        public GetUserWidgetPreferencesResponse(LMWholesale.Dealer.lmReturnValue GetUserWidgetPreferencesResult) {
            this.GetUserWidgetPreferencesResult = GetUserWidgetPreferencesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDashInventoryHealth", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetDashInventoryHealthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        public GetDashInventoryHealthRequest() {
        }
        
        public GetDashInventoryHealthRequest(string Session, int kDealer) {
            this.Session = Session;
            this.kDealer = kDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDashInventoryHealthResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetDashInventoryHealthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue GetDashInventoryHealthResult;
        
        public GetDashInventoryHealthResponse() {
        }
        
        public GetDashInventoryHealthResponse(LMWholesale.Dealer.lmReturnValue GetDashInventoryHealthResult) {
            this.GetDashInventoryHealthResult = GetDashInventoryHealthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetImportHistoryData", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetImportHistoryDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=2)]
        public int Days;
        
        public GetImportHistoryDataRequest() {
        }
        
        public GetImportHistoryDataRequest(string Session, int kDealer, int Days) {
            this.Session = Session;
            this.kDealer = kDealer;
            this.Days = Days;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetImportHistoryDataResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetImportHistoryDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue GetImportHistoryDataResult;
        
        public GetImportHistoryDataResponse() {
        }
        
        public GetImportHistoryDataResponse(LMWholesale.Dealer.lmReturnValue GetImportHistoryDataResult) {
            this.GetImportHistoryDataResult = GetImportHistoryDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DealerNameCheck", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class DealerNameCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public string DealerName;
        
        public DealerNameCheckRequest() {
        }
        
        public DealerNameCheckRequest(string kSession, string DealerName) {
            this.kSession = kSession;
            this.DealerName = DealerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DealerNameCheckResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class DealerNameCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue DealerNameCheckResult;
        
        public DealerNameCheckResponse() {
        }
        
        public DealerNameCheckResponse(LMWholesale.Dealer.lmReturnValue DealerNameCheckResult) {
            this.DealerNameCheckResult = DealerNameCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSignupPending", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetSignupPendingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        public GetSignupPendingRequest() {
        }
        
        public GetSignupPendingRequest(string Session) {
            this.Session = Session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSignupPendingResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetSignupPendingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue GetSignupPendingResult;
        
        public GetSignupPendingResponse() {
        }
        
        public GetSignupPendingResponse(LMWholesale.Dealer.lmReturnValue GetSignupPendingResult) {
            this.GetSignupPendingResult = GetSignupPendingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSignupAuctions", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetSignupAuctionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        public GetSignupAuctionsRequest() {
        }
        
        public GetSignupAuctionsRequest(string Session) {
            this.Session = Session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSignupAuctionsResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetSignupAuctionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue GetSignupAuctionsResult;
        
        public GetSignupAuctionsResponse() {
        }
        
        public GetSignupAuctionsResponse(LMWholesale.Dealer.lmReturnValue GetSignupAuctionsResult) {
            this.GetSignupAuctionsResult = GetSignupAuctionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPendingSetup", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetPendingSetupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kWholesaleSignup;
        
        public GetPendingSetupRequest() {
        }
        
        public GetPendingSetupRequest(string Session, int kWholesaleSignup) {
            this.Session = Session;
            this.kWholesaleSignup = kWholesaleSignup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPendingSetupResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetPendingSetupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue GetPendingSetupResult;
        
        public GetPendingSetupResponse() {
        }
        
        public GetPendingSetupResponse(LMWholesale.Dealer.lmReturnValue GetPendingSetupResult) {
            this.GetPendingSetupResult = GetPendingSetupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSignup", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class SetSignupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public string jsonData;
        
        public SetSignupRequest() {
        }
        
        public SetSignupRequest(string Session, string jsonData) {
            this.Session = Session;
            this.jsonData = jsonData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSignupResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class SetSignupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Dealer.lmReturnValue SetSignupResult;
        
        public SetSignupResponse() {
        }
        
        public SetSignupResponse(LMWholesale.Dealer.lmReturnValue SetSignupResult) {
            this.SetSignupResult = SetSignupResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DealerSoapChannel : LMWholesale.Dealer.DealerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DealerSoapClient : System.ServiceModel.ClientBase<LMWholesale.Dealer.DealerSoap>, LMWholesale.Dealer.DealerSoap {
        
        public DealerSoapClient() {
        }
        
        public DealerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DealerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.GetDealerInfoResponse LMWholesale.Dealer.DealerSoap.GetDealerInfo(LMWholesale.Dealer.GetDealerInfoRequest request) {
            return base.Channel.GetDealerInfo(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue GetDealerInfo(string Session, int kDealer, string SingleTable, string MultiTableName) {
            LMWholesale.Dealer.GetDealerInfoRequest inValue = new LMWholesale.Dealer.GetDealerInfoRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            inValue.SingleTable = SingleTable;
            inValue.MultiTableName = MultiTableName;
            LMWholesale.Dealer.GetDealerInfoResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).GetDealerInfo(inValue);
            return retVal.GetDealerInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetDealerInfoResponse> LMWholesale.Dealer.DealerSoap.GetDealerInfoAsync(LMWholesale.Dealer.GetDealerInfoRequest request) {
            return base.Channel.GetDealerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.GetDealerInfoResponse> GetDealerInfoAsync(string Session, int kDealer, string SingleTable, string MultiTableName) {
            LMWholesale.Dealer.GetDealerInfoRequest inValue = new LMWholesale.Dealer.GetDealerInfoRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            inValue.SingleTable = SingleTable;
            inValue.MultiTableName = MultiTableName;
            return ((LMWholesale.Dealer.DealerSoap)(this)).GetDealerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.LotLocationListGetResponse LMWholesale.Dealer.DealerSoap.LotLocationListGet(LMWholesale.Dealer.LotLocationListGetRequest request) {
            return base.Channel.LotLocationListGet(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue LotLocationListGet(string Session, int kDealer) {
            LMWholesale.Dealer.LotLocationListGetRequest inValue = new LMWholesale.Dealer.LotLocationListGetRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            LMWholesale.Dealer.LotLocationListGetResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).LotLocationListGet(inValue);
            return retVal.LotLocationListGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.LotLocationListGetResponse> LMWholesale.Dealer.DealerSoap.LotLocationListGetAsync(LMWholesale.Dealer.LotLocationListGetRequest request) {
            return base.Channel.LotLocationListGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.LotLocationListGetResponse> LotLocationListGetAsync(string Session, int kDealer) {
            LMWholesale.Dealer.LotLocationListGetRequest inValue = new LMWholesale.Dealer.LotLocationListGetRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            return ((LMWholesale.Dealer.DealerSoap)(this)).LotLocationListGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.ImportConfigGetResponse LMWholesale.Dealer.DealerSoap.ImportConfigGet(LMWholesale.Dealer.ImportConfigGetRequest request) {
            return base.Channel.ImportConfigGet(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue ImportConfigGet(string Session, int kDealer) {
            LMWholesale.Dealer.ImportConfigGetRequest inValue = new LMWholesale.Dealer.ImportConfigGetRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            LMWholesale.Dealer.ImportConfigGetResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).ImportConfigGet(inValue);
            return retVal.ImportConfigGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.ImportConfigGetResponse> LMWholesale.Dealer.DealerSoap.ImportConfigGetAsync(LMWholesale.Dealer.ImportConfigGetRequest request) {
            return base.Channel.ImportConfigGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.ImportConfigGetResponse> ImportConfigGetAsync(string Session, int kDealer) {
            LMWholesale.Dealer.ImportConfigGetRequest inValue = new LMWholesale.Dealer.ImportConfigGetRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            return ((LMWholesale.Dealer.DealerSoap)(this)).ImportConfigGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.ImportSystemGetResponse LMWholesale.Dealer.DealerSoap.ImportSystemGet(LMWholesale.Dealer.ImportSystemGetRequest request) {
            return base.Channel.ImportSystemGet(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue ImportSystemGet(string Session, string VehicleInvAcc) {
            LMWholesale.Dealer.ImportSystemGetRequest inValue = new LMWholesale.Dealer.ImportSystemGetRequest();
            inValue.Session = Session;
            inValue.VehicleInvAcc = VehicleInvAcc;
            LMWholesale.Dealer.ImportSystemGetResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).ImportSystemGet(inValue);
            return retVal.ImportSystemGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.ImportSystemGetResponse> LMWholesale.Dealer.DealerSoap.ImportSystemGetAsync(LMWholesale.Dealer.ImportSystemGetRequest request) {
            return base.Channel.ImportSystemGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.ImportSystemGetResponse> ImportSystemGetAsync(string Session, string VehicleInvAcc) {
            LMWholesale.Dealer.ImportSystemGetRequest inValue = new LMWholesale.Dealer.ImportSystemGetRequest();
            inValue.Session = Session;
            inValue.VehicleInvAcc = VehicleInvAcc;
            return ((LMWholesale.Dealer.DealerSoap)(this)).ImportSystemGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.DealerBaseSetResponse LMWholesale.Dealer.DealerSoap.DealerBaseSet(LMWholesale.Dealer.DealerBaseSetRequest request) {
            return base.Channel.DealerBaseSet(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue DealerBaseSet(string Session, string kDealer, string jsonData) {
            LMWholesale.Dealer.DealerBaseSetRequest inValue = new LMWholesale.Dealer.DealerBaseSetRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            inValue.jsonData = jsonData;
            LMWholesale.Dealer.DealerBaseSetResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).DealerBaseSet(inValue);
            return retVal.DealerBaseSetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.DealerBaseSetResponse> LMWholesale.Dealer.DealerSoap.DealerBaseSetAsync(LMWholesale.Dealer.DealerBaseSetRequest request) {
            return base.Channel.DealerBaseSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.DealerBaseSetResponse> DealerBaseSetAsync(string Session, string kDealer, string jsonData) {
            LMWholesale.Dealer.DealerBaseSetRequest inValue = new LMWholesale.Dealer.DealerBaseSetRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            inValue.jsonData = jsonData;
            return ((LMWholesale.Dealer.DealerSoap)(this)).DealerBaseSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.GetDealerPathsResponse LMWholesale.Dealer.DealerSoap.GetDealerPaths(LMWholesale.Dealer.GetDealerPathsRequest request) {
            return base.Channel.GetDealerPaths(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue GetDealerPaths(string Session, int kDealer) {
            LMWholesale.Dealer.GetDealerPathsRequest inValue = new LMWholesale.Dealer.GetDealerPathsRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            LMWholesale.Dealer.GetDealerPathsResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).GetDealerPaths(inValue);
            return retVal.GetDealerPathsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetDealerPathsResponse> LMWholesale.Dealer.DealerSoap.GetDealerPathsAsync(LMWholesale.Dealer.GetDealerPathsRequest request) {
            return base.Channel.GetDealerPathsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.GetDealerPathsResponse> GetDealerPathsAsync(string Session, int kDealer) {
            LMWholesale.Dealer.GetDealerPathsRequest inValue = new LMWholesale.Dealer.GetDealerPathsRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            return ((LMWholesale.Dealer.DealerSoap)(this)).GetDealerPathsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.GetUserWidgetPreferencesResponse LMWholesale.Dealer.DealerSoap.GetUserWidgetPreferences(LMWholesale.Dealer.GetUserWidgetPreferencesRequest request) {
            return base.Channel.GetUserWidgetPreferences(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue GetUserWidgetPreferences(string Session, int kDealer, int kWidget) {
            LMWholesale.Dealer.GetUserWidgetPreferencesRequest inValue = new LMWholesale.Dealer.GetUserWidgetPreferencesRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            inValue.kWidget = kWidget;
            LMWholesale.Dealer.GetUserWidgetPreferencesResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).GetUserWidgetPreferences(inValue);
            return retVal.GetUserWidgetPreferencesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetUserWidgetPreferencesResponse> LMWholesale.Dealer.DealerSoap.GetUserWidgetPreferencesAsync(LMWholesale.Dealer.GetUserWidgetPreferencesRequest request) {
            return base.Channel.GetUserWidgetPreferencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.GetUserWidgetPreferencesResponse> GetUserWidgetPreferencesAsync(string Session, int kDealer, int kWidget) {
            LMWholesale.Dealer.GetUserWidgetPreferencesRequest inValue = new LMWholesale.Dealer.GetUserWidgetPreferencesRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            inValue.kWidget = kWidget;
            return ((LMWholesale.Dealer.DealerSoap)(this)).GetUserWidgetPreferencesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.GetDashInventoryHealthResponse LMWholesale.Dealer.DealerSoap.GetDashInventoryHealth(LMWholesale.Dealer.GetDashInventoryHealthRequest request) {
            return base.Channel.GetDashInventoryHealth(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue GetDashInventoryHealth(string Session, int kDealer) {
            LMWholesale.Dealer.GetDashInventoryHealthRequest inValue = new LMWholesale.Dealer.GetDashInventoryHealthRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            LMWholesale.Dealer.GetDashInventoryHealthResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).GetDashInventoryHealth(inValue);
            return retVal.GetDashInventoryHealthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetDashInventoryHealthResponse> LMWholesale.Dealer.DealerSoap.GetDashInventoryHealthAsync(LMWholesale.Dealer.GetDashInventoryHealthRequest request) {
            return base.Channel.GetDashInventoryHealthAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.GetDashInventoryHealthResponse> GetDashInventoryHealthAsync(string Session, int kDealer) {
            LMWholesale.Dealer.GetDashInventoryHealthRequest inValue = new LMWholesale.Dealer.GetDashInventoryHealthRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            return ((LMWholesale.Dealer.DealerSoap)(this)).GetDashInventoryHealthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.GetImportHistoryDataResponse LMWholesale.Dealer.DealerSoap.GetImportHistoryData(LMWholesale.Dealer.GetImportHistoryDataRequest request) {
            return base.Channel.GetImportHistoryData(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue GetImportHistoryData(string Session, int kDealer, int Days) {
            LMWholesale.Dealer.GetImportHistoryDataRequest inValue = new LMWholesale.Dealer.GetImportHistoryDataRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            inValue.Days = Days;
            LMWholesale.Dealer.GetImportHistoryDataResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).GetImportHistoryData(inValue);
            return retVal.GetImportHistoryDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetImportHistoryDataResponse> LMWholesale.Dealer.DealerSoap.GetImportHistoryDataAsync(LMWholesale.Dealer.GetImportHistoryDataRequest request) {
            return base.Channel.GetImportHistoryDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.GetImportHistoryDataResponse> GetImportHistoryDataAsync(string Session, int kDealer, int Days) {
            LMWholesale.Dealer.GetImportHistoryDataRequest inValue = new LMWholesale.Dealer.GetImportHistoryDataRequest();
            inValue.Session = Session;
            inValue.kDealer = kDealer;
            inValue.Days = Days;
            return ((LMWholesale.Dealer.DealerSoap)(this)).GetImportHistoryDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.DealerNameCheckResponse LMWholesale.Dealer.DealerSoap.DealerNameCheck(LMWholesale.Dealer.DealerNameCheckRequest request) {
            return base.Channel.DealerNameCheck(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue DealerNameCheck(string kSession, string DealerName) {
            LMWholesale.Dealer.DealerNameCheckRequest inValue = new LMWholesale.Dealer.DealerNameCheckRequest();
            inValue.kSession = kSession;
            inValue.DealerName = DealerName;
            LMWholesale.Dealer.DealerNameCheckResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).DealerNameCheck(inValue);
            return retVal.DealerNameCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.DealerNameCheckResponse> LMWholesale.Dealer.DealerSoap.DealerNameCheckAsync(LMWholesale.Dealer.DealerNameCheckRequest request) {
            return base.Channel.DealerNameCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.DealerNameCheckResponse> DealerNameCheckAsync(string kSession, string DealerName) {
            LMWholesale.Dealer.DealerNameCheckRequest inValue = new LMWholesale.Dealer.DealerNameCheckRequest();
            inValue.kSession = kSession;
            inValue.DealerName = DealerName;
            return ((LMWholesale.Dealer.DealerSoap)(this)).DealerNameCheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.GetSignupPendingResponse LMWholesale.Dealer.DealerSoap.GetSignupPending(LMWholesale.Dealer.GetSignupPendingRequest request) {
            return base.Channel.GetSignupPending(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue GetSignupPending(string Session) {
            LMWholesale.Dealer.GetSignupPendingRequest inValue = new LMWholesale.Dealer.GetSignupPendingRequest();
            inValue.Session = Session;
            LMWholesale.Dealer.GetSignupPendingResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).GetSignupPending(inValue);
            return retVal.GetSignupPendingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetSignupPendingResponse> LMWholesale.Dealer.DealerSoap.GetSignupPendingAsync(LMWholesale.Dealer.GetSignupPendingRequest request) {
            return base.Channel.GetSignupPendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.GetSignupPendingResponse> GetSignupPendingAsync(string Session) {
            LMWholesale.Dealer.GetSignupPendingRequest inValue = new LMWholesale.Dealer.GetSignupPendingRequest();
            inValue.Session = Session;
            return ((LMWholesale.Dealer.DealerSoap)(this)).GetSignupPendingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.GetSignupAuctionsResponse LMWholesale.Dealer.DealerSoap.GetSignupAuctions(LMWholesale.Dealer.GetSignupAuctionsRequest request) {
            return base.Channel.GetSignupAuctions(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue GetSignupAuctions(string Session) {
            LMWholesale.Dealer.GetSignupAuctionsRequest inValue = new LMWholesale.Dealer.GetSignupAuctionsRequest();
            inValue.Session = Session;
            LMWholesale.Dealer.GetSignupAuctionsResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).GetSignupAuctions(inValue);
            return retVal.GetSignupAuctionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetSignupAuctionsResponse> LMWholesale.Dealer.DealerSoap.GetSignupAuctionsAsync(LMWholesale.Dealer.GetSignupAuctionsRequest request) {
            return base.Channel.GetSignupAuctionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.GetSignupAuctionsResponse> GetSignupAuctionsAsync(string Session) {
            LMWholesale.Dealer.GetSignupAuctionsRequest inValue = new LMWholesale.Dealer.GetSignupAuctionsRequest();
            inValue.Session = Session;
            return ((LMWholesale.Dealer.DealerSoap)(this)).GetSignupAuctionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.GetPendingSetupResponse LMWholesale.Dealer.DealerSoap.GetPendingSetup(LMWholesale.Dealer.GetPendingSetupRequest request) {
            return base.Channel.GetPendingSetup(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue GetPendingSetup(string Session, int kWholesaleSignup) {
            LMWholesale.Dealer.GetPendingSetupRequest inValue = new LMWholesale.Dealer.GetPendingSetupRequest();
            inValue.Session = Session;
            inValue.kWholesaleSignup = kWholesaleSignup;
            LMWholesale.Dealer.GetPendingSetupResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).GetPendingSetup(inValue);
            return retVal.GetPendingSetupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.GetPendingSetupResponse> LMWholesale.Dealer.DealerSoap.GetPendingSetupAsync(LMWholesale.Dealer.GetPendingSetupRequest request) {
            return base.Channel.GetPendingSetupAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.GetPendingSetupResponse> GetPendingSetupAsync(string Session, int kWholesaleSignup) {
            LMWholesale.Dealer.GetPendingSetupRequest inValue = new LMWholesale.Dealer.GetPendingSetupRequest();
            inValue.Session = Session;
            inValue.kWholesaleSignup = kWholesaleSignup;
            return ((LMWholesale.Dealer.DealerSoap)(this)).GetPendingSetupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Dealer.SetSignupResponse LMWholesale.Dealer.DealerSoap.SetSignup(LMWholesale.Dealer.SetSignupRequest request) {
            return base.Channel.SetSignup(request);
        }
        
        public LMWholesale.Dealer.lmReturnValue SetSignup(string Session, string jsonData) {
            LMWholesale.Dealer.SetSignupRequest inValue = new LMWholesale.Dealer.SetSignupRequest();
            inValue.Session = Session;
            inValue.jsonData = jsonData;
            LMWholesale.Dealer.SetSignupResponse retVal = ((LMWholesale.Dealer.DealerSoap)(this)).SetSignup(inValue);
            return retVal.SetSignupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Dealer.SetSignupResponse> LMWholesale.Dealer.DealerSoap.SetSignupAsync(LMWholesale.Dealer.SetSignupRequest request) {
            return base.Channel.SetSignupAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Dealer.SetSignupResponse> SetSignupAsync(string Session, string jsonData) {
            LMWholesale.Dealer.SetSignupRequest inValue = new LMWholesale.Dealer.SetSignupRequest();
            inValue.Session = Session;
            inValue.jsonData = jsonData;
            return ((LMWholesale.Dealer.DealerSoap)(this)).SetSignupAsync(inValue);
        }
    }
}
