//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMWholesale.Lookup {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.liquidmotors.com", ConfigurationName="Lookup.LookupSoap")]
    public interface LookupSoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetDealerListRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetDealerList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GetDealerListResponse GetDealerList(LMWholesale.Lookup.GetDealerListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetDealerList", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetDealerListResponse> GetDealerListAsync(LMWholesale.Lookup.GetDealerListRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetListingOptionListRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetListingOptionList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GetListingOptionListResponse GetListingOptionList(LMWholesale.Lookup.GetListingOptionListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetListingOptionList", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetListingOptionListResponse> GetListingOptionListAsync(LMWholesale.Lookup.GetListingOptionListRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetMakeListRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetMakeList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GetMakeListResponse GetMakeList(LMWholesale.Lookup.GetMakeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetMakeList", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetMakeListResponse> GetMakeListAsync(LMWholesale.Lookup.GetMakeListRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetModelListRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetModelList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GetModelListResponse GetModelList(LMWholesale.Lookup.GetModelListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetModelList", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetModelListResponse> GetModelListAsync(LMWholesale.Lookup.GetModelListRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message InspectionCompanyListGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/InspectionCompanyListGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.InspectionCompanyListGetResponse InspectionCompanyListGet(LMWholesale.Lookup.InspectionCompanyListGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/InspectionCompanyListGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.InspectionCompanyListGetResponse> InspectionCompanyListGetAsync(LMWholesale.Lookup.InspectionCompanyListGetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetListingsByVINRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetListingsByVIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GetListingsByVINResponse GetListingsByVIN(LMWholesale.Lookup.GetListingsByVINRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetListingsByVIN", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetListingsByVINResponse> GetListingsByVINAsync(LMWholesale.Lookup.GetListingsByVINRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetMultiAuctionCredentialsByDealerRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetMultiAuctionCredentialsByDealer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerResponse GetMultiAuctionCredentialsByDealer(LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetMultiAuctionCredentialsByDealer", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerResponse> GetMultiAuctionCredentialsByDealerAsync(LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetAuctionCredentialsByDealerByAuctionRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetAuctionCredentialsByDealerByAuction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionResponse GetAuctionCredentialsByDealerByAuction(LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetAuctionCredentialsByDealerByAuction", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionResponse> GetAuctionCredentialsByDealerByAuctionAsync(LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetWholesaleAuctionFuelTypeRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetWholesaleAuctionFuelType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GetWholesaleAuctionFuelTypeResponse GetWholesaleAuctionFuelType(LMWholesale.Lookup.GetWholesaleAuctionFuelTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetWholesaleAuctionFuelType", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetWholesaleAuctionFuelTypeResponse> GetWholesaleAuctionFuelTypeAsync(LMWholesale.Lookup.GetWholesaleAuctionFuelTypeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message WholesaleUserDefaultUserGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/WholesaleUserDefaultUserGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.WholesaleUserDefaultUserGetResponse WholesaleUserDefaultUserGet(LMWholesale.Lookup.WholesaleUserDefaultUserGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/WholesaleUserDefaultUserGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.WholesaleUserDefaultUserGetResponse> WholesaleUserDefaultUserGetAsync(LMWholesale.Lookup.WholesaleUserDefaultUserGetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GridDescriptionGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GridDescriptionGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.GridDescriptionGetResponse GridDescriptionGet(LMWholesale.Lookup.GridDescriptionGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GridDescriptionGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GridDescriptionGetResponse> GridDescriptionGetAsync(LMWholesale.Lookup.GridDescriptionGetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message UserListGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/UserListGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.UserListGetResponse UserListGet(LMWholesale.Lookup.UserListGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/UserListGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.UserListGetResponse> UserListGetAsync(LMWholesale.Lookup.UserListGetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message PhotoTagListGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/PhotoTagListGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.PhotoTagListGetResponse PhotoTagListGet(LMWholesale.Lookup.PhotoTagListGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/PhotoTagListGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.PhotoTagListGetResponse> PhotoTagListGetAsync(LMWholesale.Lookup.PhotoTagListGetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message CertificationListGetRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/CertificationListGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Lookup.CertificationListGetResponse CertificationListGet(LMWholesale.Lookup.CertificationListGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/CertificationListGet", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Lookup.CertificationListGetResponse> CertificationListGetAsync(LMWholesale.Lookup.CertificationListGetRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class lmReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SerializableDictionary valuesField;
        
        private ReturnCode resultField;
        
        private string resultStringField;
        
        private System.Data.DataSet dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SerializableDictionary Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReturnCode Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResultString {
            get {
                return this.resultStringField;
            }
            set {
                this.resultStringField = value;
                this.RaisePropertyChanged("ResultString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Data.DataSet Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class SerializableDictionary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyValuePair[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public KeyValuePair[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class KeyValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public enum ReturnCode {
        
        /// <remarks/>
        LM_SUCCESS,
        
        /// <remarks/>
        LM_INVALIDSESSION,
        
        /// <remarks/>
        LM_RELAYCOMMERROR,
        
        /// <remarks/>
        LM_DBERROR,
        
        /// <remarks/>
        LM_MISSINGASSOCIATIONS,
        
        /// <remarks/>
        LM_GENERICERROR,
        
        /// <remarks/>
        LM_SECURITYERROR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDealerList", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetDealerListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        public GetDealerListRequest() {
        }
        
        public GetDealerListRequest(string kSession) {
            this.kSession = kSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDealerListResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetDealerListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GetDealerListResult;
        
        public GetDealerListResponse() {
        }
        
        public GetDealerListResponse(LMWholesale.Lookup.lmReturnValue GetDealerListResult) {
            this.GetDealerListResult = GetDealerListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListingOptionList", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetListingOptionListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kListing;
        
        public GetListingOptionListRequest() {
        }
        
        public GetListingOptionListRequest(string kSession, int kListing) {
            this.kSession = kSession;
            this.kListing = kListing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListingOptionListResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetListingOptionListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GetListingOptionListResult;
        
        public GetListingOptionListResponse() {
        }
        
        public GetListingOptionListResponse(LMWholesale.Lookup.lmReturnValue GetListingOptionListResult) {
            this.GetListingOptionListResult = GetListingOptionListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMakeList", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetMakeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        public GetMakeListRequest() {
        }
        
        public GetMakeListRequest(string kSession) {
            this.kSession = kSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMakeListResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetMakeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GetMakeListResult;
        
        public GetMakeListResponse() {
        }
        
        public GetMakeListResponse(LMWholesale.Lookup.lmReturnValue GetMakeListResult) {
            this.GetMakeListResult = GetMakeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelList", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetModelListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kMake;
        
        public GetModelListRequest() {
        }
        
        public GetModelListRequest(string kSession, int kMake) {
            this.kSession = kSession;
            this.kMake = kMake;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetModelListResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetModelListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GetModelListResult;
        
        public GetModelListResponse() {
        }
        
        public GetModelListResponse(LMWholesale.Lookup.lmReturnValue GetModelListResult) {
            this.GetModelListResult = GetModelListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InspectionCompanyListGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class InspectionCompanyListGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=2)]
        public int kListing;
        
        public InspectionCompanyListGetRequest() {
        }
        
        public InspectionCompanyListGetRequest(string kSession, int kDealer, int kListing) {
            this.kSession = kSession;
            this.kDealer = kDealer;
            this.kListing = kListing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InspectionCompanyListGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class InspectionCompanyListGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue InspectionCompanyListGetResult;
        
        public InspectionCompanyListGetResponse() {
        }
        
        public InspectionCompanyListGetResponse(LMWholesale.Lookup.lmReturnValue InspectionCompanyListGetResult) {
            this.InspectionCompanyListGetResult = InspectionCompanyListGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListingsByVIN", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetListingsByVINRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public string vin;
        
        public GetListingsByVINRequest() {
        }
        
        public GetListingsByVINRequest(string kSession, string vin) {
            this.kSession = kSession;
            this.vin = vin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListingsByVINResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetListingsByVINResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GetListingsByVINResult;
        
        public GetListingsByVINResponse() {
        }
        
        public GetListingsByVINResponse(LMWholesale.Lookup.lmReturnValue GetListingsByVINResult) {
            this.GetListingsByVINResult = GetListingsByVINResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiAuctionCredentialsByDealer", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetMultiAuctionCredentialsByDealerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public string kDealer;
        
        public GetMultiAuctionCredentialsByDealerRequest() {
        }
        
        public GetMultiAuctionCredentialsByDealerRequest(string kSession, string kDealer) {
            this.kSession = kSession;
            this.kDealer = kDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiAuctionCredentialsByDealerResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetMultiAuctionCredentialsByDealerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GetMultiAuctionCredentialsByDealerResult;
        
        public GetMultiAuctionCredentialsByDealerResponse() {
        }
        
        public GetMultiAuctionCredentialsByDealerResponse(LMWholesale.Lookup.lmReturnValue GetMultiAuctionCredentialsByDealerResult) {
            this.GetMultiAuctionCredentialsByDealerResult = GetMultiAuctionCredentialsByDealerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuctionCredentialsByDealerByAuction", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetAuctionCredentialsByDealerByAuctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public string kDealer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=2)]
        public string kWholesaleAuction;
        
        public GetAuctionCredentialsByDealerByAuctionRequest() {
        }
        
        public GetAuctionCredentialsByDealerByAuctionRequest(string kSession, string kDealer, string kWholesaleAuction) {
            this.kSession = kSession;
            this.kDealer = kDealer;
            this.kWholesaleAuction = kWholesaleAuction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuctionCredentialsByDealerByAuctionResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetAuctionCredentialsByDealerByAuctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GetAuctionCredentialsByDealerByAuctionResult;
        
        public GetAuctionCredentialsByDealerByAuctionResponse() {
        }
        
        public GetAuctionCredentialsByDealerByAuctionResponse(LMWholesale.Lookup.lmReturnValue GetAuctionCredentialsByDealerByAuctionResult) {
            this.GetAuctionCredentialsByDealerByAuctionResult = GetAuctionCredentialsByDealerByAuctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWholesaleAuctionFuelType", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetWholesaleAuctionFuelTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        public GetWholesaleAuctionFuelTypeRequest() {
        }
        
        public GetWholesaleAuctionFuelTypeRequest(string kSession) {
            this.kSession = kSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWholesaleAuctionFuelTypeResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetWholesaleAuctionFuelTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GetWholesaleAuctionFuelTypeResult;
        
        public GetWholesaleAuctionFuelTypeResponse() {
        }
        
        public GetWholesaleAuctionFuelTypeResponse(LMWholesale.Lookup.lmReturnValue GetWholesaleAuctionFuelTypeResult) {
            this.GetWholesaleAuctionFuelTypeResult = GetWholesaleAuctionFuelTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WholesaleUserDefaultUserGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class WholesaleUserDefaultUserGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        public WholesaleUserDefaultUserGetRequest() {
        }
        
        public WholesaleUserDefaultUserGetRequest(string kSession, int kDealer) {
            this.kSession = kSession;
            this.kDealer = kDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WholesaleUserDefaultUserGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class WholesaleUserDefaultUserGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue WholesaleUserDefaultUserGetResult;
        
        public WholesaleUserDefaultUserGetResponse() {
        }
        
        public WholesaleUserDefaultUserGetResponse(LMWholesale.Lookup.lmReturnValue WholesaleUserDefaultUserGetResult) {
            this.WholesaleUserDefaultUserGetResult = WholesaleUserDefaultUserGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GridDescriptionGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GridDescriptionGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kDealer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=2)]
        public int kPerson;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=3)]
        public string GridDescription;
        
        public GridDescriptionGetRequest() {
        }
        
        public GridDescriptionGetRequest(string kSession, int kDealer, int kPerson, string GridDescription) {
            this.kSession = kSession;
            this.kDealer = kDealer;
            this.kPerson = kPerson;
            this.GridDescription = GridDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GridDescriptionGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GridDescriptionGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue GridDescriptionGetResult;
        
        public GridDescriptionGetResponse() {
        }
        
        public GridDescriptionGetResponse(LMWholesale.Lookup.lmReturnValue GridDescriptionGetResult) {
            this.GridDescriptionGetResult = GridDescriptionGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserListGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class UserListGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kExceptDealer;
        
        public UserListGetRequest() {
        }
        
        public UserListGetRequest(string kSession, int kExceptDealer) {
            this.kSession = kSession;
            this.kExceptDealer = kExceptDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserListGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class UserListGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue UserListGetResult;
        
        public UserListGetResponse() {
        }
        
        public UserListGetResponse(LMWholesale.Lookup.lmReturnValue UserListGetResult) {
            this.UserListGetResult = UserListGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PhotoTagListGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class PhotoTagListGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        public PhotoTagListGetRequest() {
        }
        
        public PhotoTagListGetRequest(string kSession) {
            this.kSession = kSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PhotoTagListGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class PhotoTagListGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue PhotoTagListGetResult;
        
        public PhotoTagListGetResponse() {
        }
        
        public PhotoTagListGetResponse(LMWholesale.Lookup.lmReturnValue PhotoTagListGetResult) {
            this.PhotoTagListGetResult = PhotoTagListGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CertificationListGet", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class CertificationListGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string kSession;
        
        public CertificationListGetRequest() {
        }
        
        public CertificationListGetRequest(string kSession) {
            this.kSession = kSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CertificationListGetResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class CertificationListGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Lookup.lmReturnValue CertificationListGetResult;
        
        public CertificationListGetResponse() {
        }
        
        public CertificationListGetResponse(LMWholesale.Lookup.lmReturnValue CertificationListGetResult) {
            this.CertificationListGetResult = CertificationListGetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LookupSoapChannel : LMWholesale.Lookup.LookupSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LookupSoapClient : System.ServiceModel.ClientBase<LMWholesale.Lookup.LookupSoap>, LMWholesale.Lookup.LookupSoap {
        
        public LookupSoapClient() {
        }
        
        public LookupSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LookupSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GetDealerListResponse LMWholesale.Lookup.LookupSoap.GetDealerList(LMWholesale.Lookup.GetDealerListRequest request) {
            return base.Channel.GetDealerList(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GetDealerList(string kSession) {
            LMWholesale.Lookup.GetDealerListRequest inValue = new LMWholesale.Lookup.GetDealerListRequest();
            inValue.kSession = kSession;
            LMWholesale.Lookup.GetDealerListResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GetDealerList(inValue);
            return retVal.GetDealerListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetDealerListResponse> LMWholesale.Lookup.LookupSoap.GetDealerListAsync(LMWholesale.Lookup.GetDealerListRequest request) {
            return base.Channel.GetDealerListAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GetDealerListResponse> GetDealerListAsync(string kSession) {
            LMWholesale.Lookup.GetDealerListRequest inValue = new LMWholesale.Lookup.GetDealerListRequest();
            inValue.kSession = kSession;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GetDealerListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GetListingOptionListResponse LMWholesale.Lookup.LookupSoap.GetListingOptionList(LMWholesale.Lookup.GetListingOptionListRequest request) {
            return base.Channel.GetListingOptionList(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GetListingOptionList(string kSession, int kListing) {
            LMWholesale.Lookup.GetListingOptionListRequest inValue = new LMWholesale.Lookup.GetListingOptionListRequest();
            inValue.kSession = kSession;
            inValue.kListing = kListing;
            LMWholesale.Lookup.GetListingOptionListResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GetListingOptionList(inValue);
            return retVal.GetListingOptionListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetListingOptionListResponse> LMWholesale.Lookup.LookupSoap.GetListingOptionListAsync(LMWholesale.Lookup.GetListingOptionListRequest request) {
            return base.Channel.GetListingOptionListAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GetListingOptionListResponse> GetListingOptionListAsync(string kSession, int kListing) {
            LMWholesale.Lookup.GetListingOptionListRequest inValue = new LMWholesale.Lookup.GetListingOptionListRequest();
            inValue.kSession = kSession;
            inValue.kListing = kListing;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GetListingOptionListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GetMakeListResponse LMWholesale.Lookup.LookupSoap.GetMakeList(LMWholesale.Lookup.GetMakeListRequest request) {
            return base.Channel.GetMakeList(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GetMakeList(string kSession) {
            LMWholesale.Lookup.GetMakeListRequest inValue = new LMWholesale.Lookup.GetMakeListRequest();
            inValue.kSession = kSession;
            LMWholesale.Lookup.GetMakeListResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GetMakeList(inValue);
            return retVal.GetMakeListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetMakeListResponse> LMWholesale.Lookup.LookupSoap.GetMakeListAsync(LMWholesale.Lookup.GetMakeListRequest request) {
            return base.Channel.GetMakeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GetMakeListResponse> GetMakeListAsync(string kSession) {
            LMWholesale.Lookup.GetMakeListRequest inValue = new LMWholesale.Lookup.GetMakeListRequest();
            inValue.kSession = kSession;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GetMakeListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GetModelListResponse LMWholesale.Lookup.LookupSoap.GetModelList(LMWholesale.Lookup.GetModelListRequest request) {
            return base.Channel.GetModelList(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GetModelList(string kSession, int kMake) {
            LMWholesale.Lookup.GetModelListRequest inValue = new LMWholesale.Lookup.GetModelListRequest();
            inValue.kSession = kSession;
            inValue.kMake = kMake;
            LMWholesale.Lookup.GetModelListResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GetModelList(inValue);
            return retVal.GetModelListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetModelListResponse> LMWholesale.Lookup.LookupSoap.GetModelListAsync(LMWholesale.Lookup.GetModelListRequest request) {
            return base.Channel.GetModelListAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GetModelListResponse> GetModelListAsync(string kSession, int kMake) {
            LMWholesale.Lookup.GetModelListRequest inValue = new LMWholesale.Lookup.GetModelListRequest();
            inValue.kSession = kSession;
            inValue.kMake = kMake;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GetModelListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.InspectionCompanyListGetResponse LMWholesale.Lookup.LookupSoap.InspectionCompanyListGet(LMWholesale.Lookup.InspectionCompanyListGetRequest request) {
            return base.Channel.InspectionCompanyListGet(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue InspectionCompanyListGet(string kSession, int kDealer, int kListing) {
            LMWholesale.Lookup.InspectionCompanyListGetRequest inValue = new LMWholesale.Lookup.InspectionCompanyListGetRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            inValue.kListing = kListing;
            LMWholesale.Lookup.InspectionCompanyListGetResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).InspectionCompanyListGet(inValue);
            return retVal.InspectionCompanyListGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.InspectionCompanyListGetResponse> LMWholesale.Lookup.LookupSoap.InspectionCompanyListGetAsync(LMWholesale.Lookup.InspectionCompanyListGetRequest request) {
            return base.Channel.InspectionCompanyListGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.InspectionCompanyListGetResponse> InspectionCompanyListGetAsync(string kSession, int kDealer, int kListing) {
            LMWholesale.Lookup.InspectionCompanyListGetRequest inValue = new LMWholesale.Lookup.InspectionCompanyListGetRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            inValue.kListing = kListing;
            return ((LMWholesale.Lookup.LookupSoap)(this)).InspectionCompanyListGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GetListingsByVINResponse LMWholesale.Lookup.LookupSoap.GetListingsByVIN(LMWholesale.Lookup.GetListingsByVINRequest request) {
            return base.Channel.GetListingsByVIN(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GetListingsByVIN(string kSession, string vin) {
            LMWholesale.Lookup.GetListingsByVINRequest inValue = new LMWholesale.Lookup.GetListingsByVINRequest();
            inValue.kSession = kSession;
            inValue.vin = vin;
            LMWholesale.Lookup.GetListingsByVINResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GetListingsByVIN(inValue);
            return retVal.GetListingsByVINResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetListingsByVINResponse> LMWholesale.Lookup.LookupSoap.GetListingsByVINAsync(LMWholesale.Lookup.GetListingsByVINRequest request) {
            return base.Channel.GetListingsByVINAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GetListingsByVINResponse> GetListingsByVINAsync(string kSession, string vin) {
            LMWholesale.Lookup.GetListingsByVINRequest inValue = new LMWholesale.Lookup.GetListingsByVINRequest();
            inValue.kSession = kSession;
            inValue.vin = vin;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GetListingsByVINAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerResponse LMWholesale.Lookup.LookupSoap.GetMultiAuctionCredentialsByDealer(LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerRequest request) {
            return base.Channel.GetMultiAuctionCredentialsByDealer(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GetMultiAuctionCredentialsByDealer(string kSession, string kDealer) {
            LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerRequest inValue = new LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GetMultiAuctionCredentialsByDealer(inValue);
            return retVal.GetMultiAuctionCredentialsByDealerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerResponse> LMWholesale.Lookup.LookupSoap.GetMultiAuctionCredentialsByDealerAsync(LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerRequest request) {
            return base.Channel.GetMultiAuctionCredentialsByDealerAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerResponse> GetMultiAuctionCredentialsByDealerAsync(string kSession, string kDealer) {
            LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerRequest inValue = new LMWholesale.Lookup.GetMultiAuctionCredentialsByDealerRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GetMultiAuctionCredentialsByDealerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionResponse LMWholesale.Lookup.LookupSoap.GetAuctionCredentialsByDealerByAuction(LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionRequest request) {
            return base.Channel.GetAuctionCredentialsByDealerByAuction(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GetAuctionCredentialsByDealerByAuction(string kSession, string kDealer, string kWholesaleAuction) {
            LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionRequest inValue = new LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            inValue.kWholesaleAuction = kWholesaleAuction;
            LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GetAuctionCredentialsByDealerByAuction(inValue);
            return retVal.GetAuctionCredentialsByDealerByAuctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionResponse> LMWholesale.Lookup.LookupSoap.GetAuctionCredentialsByDealerByAuctionAsync(LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionRequest request) {
            return base.Channel.GetAuctionCredentialsByDealerByAuctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionResponse> GetAuctionCredentialsByDealerByAuctionAsync(string kSession, string kDealer, string kWholesaleAuction) {
            LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionRequest inValue = new LMWholesale.Lookup.GetAuctionCredentialsByDealerByAuctionRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            inValue.kWholesaleAuction = kWholesaleAuction;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GetAuctionCredentialsByDealerByAuctionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GetWholesaleAuctionFuelTypeResponse LMWholesale.Lookup.LookupSoap.GetWholesaleAuctionFuelType(LMWholesale.Lookup.GetWholesaleAuctionFuelTypeRequest request) {
            return base.Channel.GetWholesaleAuctionFuelType(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GetWholesaleAuctionFuelType(string kSession) {
            LMWholesale.Lookup.GetWholesaleAuctionFuelTypeRequest inValue = new LMWholesale.Lookup.GetWholesaleAuctionFuelTypeRequest();
            inValue.kSession = kSession;
            LMWholesale.Lookup.GetWholesaleAuctionFuelTypeResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GetWholesaleAuctionFuelType(inValue);
            return retVal.GetWholesaleAuctionFuelTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GetWholesaleAuctionFuelTypeResponse> LMWholesale.Lookup.LookupSoap.GetWholesaleAuctionFuelTypeAsync(LMWholesale.Lookup.GetWholesaleAuctionFuelTypeRequest request) {
            return base.Channel.GetWholesaleAuctionFuelTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GetWholesaleAuctionFuelTypeResponse> GetWholesaleAuctionFuelTypeAsync(string kSession) {
            LMWholesale.Lookup.GetWholesaleAuctionFuelTypeRequest inValue = new LMWholesale.Lookup.GetWholesaleAuctionFuelTypeRequest();
            inValue.kSession = kSession;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GetWholesaleAuctionFuelTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.WholesaleUserDefaultUserGetResponse LMWholesale.Lookup.LookupSoap.WholesaleUserDefaultUserGet(LMWholesale.Lookup.WholesaleUserDefaultUserGetRequest request) {
            return base.Channel.WholesaleUserDefaultUserGet(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue WholesaleUserDefaultUserGet(string kSession, int kDealer) {
            LMWholesale.Lookup.WholesaleUserDefaultUserGetRequest inValue = new LMWholesale.Lookup.WholesaleUserDefaultUserGetRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            LMWholesale.Lookup.WholesaleUserDefaultUserGetResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).WholesaleUserDefaultUserGet(inValue);
            return retVal.WholesaleUserDefaultUserGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.WholesaleUserDefaultUserGetResponse> LMWholesale.Lookup.LookupSoap.WholesaleUserDefaultUserGetAsync(LMWholesale.Lookup.WholesaleUserDefaultUserGetRequest request) {
            return base.Channel.WholesaleUserDefaultUserGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.WholesaleUserDefaultUserGetResponse> WholesaleUserDefaultUserGetAsync(string kSession, int kDealer) {
            LMWholesale.Lookup.WholesaleUserDefaultUserGetRequest inValue = new LMWholesale.Lookup.WholesaleUserDefaultUserGetRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            return ((LMWholesale.Lookup.LookupSoap)(this)).WholesaleUserDefaultUserGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.GridDescriptionGetResponse LMWholesale.Lookup.LookupSoap.GridDescriptionGet(LMWholesale.Lookup.GridDescriptionGetRequest request) {
            return base.Channel.GridDescriptionGet(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue GridDescriptionGet(string kSession, int kDealer, int kPerson, string GridDescription) {
            LMWholesale.Lookup.GridDescriptionGetRequest inValue = new LMWholesale.Lookup.GridDescriptionGetRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            inValue.kPerson = kPerson;
            inValue.GridDescription = GridDescription;
            LMWholesale.Lookup.GridDescriptionGetResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).GridDescriptionGet(inValue);
            return retVal.GridDescriptionGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.GridDescriptionGetResponse> LMWholesale.Lookup.LookupSoap.GridDescriptionGetAsync(LMWholesale.Lookup.GridDescriptionGetRequest request) {
            return base.Channel.GridDescriptionGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.GridDescriptionGetResponse> GridDescriptionGetAsync(string kSession, int kDealer, int kPerson, string GridDescription) {
            LMWholesale.Lookup.GridDescriptionGetRequest inValue = new LMWholesale.Lookup.GridDescriptionGetRequest();
            inValue.kSession = kSession;
            inValue.kDealer = kDealer;
            inValue.kPerson = kPerson;
            inValue.GridDescription = GridDescription;
            return ((LMWholesale.Lookup.LookupSoap)(this)).GridDescriptionGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.UserListGetResponse LMWholesale.Lookup.LookupSoap.UserListGet(LMWholesale.Lookup.UserListGetRequest request) {
            return base.Channel.UserListGet(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue UserListGet(string kSession, int kExceptDealer) {
            LMWholesale.Lookup.UserListGetRequest inValue = new LMWholesale.Lookup.UserListGetRequest();
            inValue.kSession = kSession;
            inValue.kExceptDealer = kExceptDealer;
            LMWholesale.Lookup.UserListGetResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).UserListGet(inValue);
            return retVal.UserListGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.UserListGetResponse> LMWholesale.Lookup.LookupSoap.UserListGetAsync(LMWholesale.Lookup.UserListGetRequest request) {
            return base.Channel.UserListGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.UserListGetResponse> UserListGetAsync(string kSession, int kExceptDealer) {
            LMWholesale.Lookup.UserListGetRequest inValue = new LMWholesale.Lookup.UserListGetRequest();
            inValue.kSession = kSession;
            inValue.kExceptDealer = kExceptDealer;
            return ((LMWholesale.Lookup.LookupSoap)(this)).UserListGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.PhotoTagListGetResponse LMWholesale.Lookup.LookupSoap.PhotoTagListGet(LMWholesale.Lookup.PhotoTagListGetRequest request) {
            return base.Channel.PhotoTagListGet(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue PhotoTagListGet(string kSession) {
            LMWholesale.Lookup.PhotoTagListGetRequest inValue = new LMWholesale.Lookup.PhotoTagListGetRequest();
            inValue.kSession = kSession;
            LMWholesale.Lookup.PhotoTagListGetResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).PhotoTagListGet(inValue);
            return retVal.PhotoTagListGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.PhotoTagListGetResponse> LMWholesale.Lookup.LookupSoap.PhotoTagListGetAsync(LMWholesale.Lookup.PhotoTagListGetRequest request) {
            return base.Channel.PhotoTagListGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.PhotoTagListGetResponse> PhotoTagListGetAsync(string kSession) {
            LMWholesale.Lookup.PhotoTagListGetRequest inValue = new LMWholesale.Lookup.PhotoTagListGetRequest();
            inValue.kSession = kSession;
            return ((LMWholesale.Lookup.LookupSoap)(this)).PhotoTagListGetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Lookup.CertificationListGetResponse LMWholesale.Lookup.LookupSoap.CertificationListGet(LMWholesale.Lookup.CertificationListGetRequest request) {
            return base.Channel.CertificationListGet(request);
        }
        
        public LMWholesale.Lookup.lmReturnValue CertificationListGet(string kSession) {
            LMWholesale.Lookup.CertificationListGetRequest inValue = new LMWholesale.Lookup.CertificationListGetRequest();
            inValue.kSession = kSession;
            LMWholesale.Lookup.CertificationListGetResponse retVal = ((LMWholesale.Lookup.LookupSoap)(this)).CertificationListGet(inValue);
            return retVal.CertificationListGetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Lookup.CertificationListGetResponse> LMWholesale.Lookup.LookupSoap.CertificationListGetAsync(LMWholesale.Lookup.CertificationListGetRequest request) {
            return base.Channel.CertificationListGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Lookup.CertificationListGetResponse> CertificationListGetAsync(string kSession) {
            LMWholesale.Lookup.CertificationListGetRequest inValue = new LMWholesale.Lookup.CertificationListGetRequest();
            inValue.kSession = kSession;
            return ((LMWholesale.Lookup.LookupSoap)(this)).CertificationListGetAsync(inValue);
        }
    }
}
