//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMWholesale.Inventory {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.liquidmotors.com", ConfigurationName="Inventory.InventorySoap")]
    public interface InventorySoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message GetInventoryOverridesRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetInventoryOverrides", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Inventory.GetInventoryOverridesResponse GetInventoryOverrides(LMWholesale.Inventory.GetInventoryOverridesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/GetInventoryOverrides", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Inventory.GetInventoryOverridesResponse> GetInventoryOverridesAsync(LMWholesale.Inventory.GetInventoryOverridesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://liquidmotors.com/webservices/) of message SetInventoryOverridesRequest does not match the default value (http://services.liquidmotors.com)
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/SetInventoryOverrides", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LMWholesale.Inventory.SetInventoryOverridesResponse SetInventoryOverrides(LMWholesale.Inventory.SetInventoryOverridesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://liquidmotors.com/webservices/SetInventoryOverrides", ReplyAction="*")]
        System.Threading.Tasks.Task<LMWholesale.Inventory.SetInventoryOverridesResponse> SetInventoryOverridesAsync(LMWholesale.Inventory.SetInventoryOverridesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class lmReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SerializableDictionary valuesField;
        
        private ReturnCode resultField;
        
        private string resultStringField;
        
        private System.Data.DataSet dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SerializableDictionary Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReturnCode Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResultString {
            get {
                return this.resultStringField;
            }
            set {
                this.resultStringField = value;
                this.RaisePropertyChanged("ResultString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Data.DataSet Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class SerializableDictionary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyValuePair[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public KeyValuePair[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public partial class KeyValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://liquidmotors.com/webservices/")]
    public enum ReturnCode {
        
        /// <remarks/>
        LM_SUCCESS,
        
        /// <remarks/>
        LM_INVALIDSESSION,
        
        /// <remarks/>
        LM_RELAYCOMMERROR,
        
        /// <remarks/>
        LM_DBERROR,
        
        /// <remarks/>
        LM_MISSINGASSOCIATIONS,
        
        /// <remarks/>
        LM_GENERICERROR,
        
        /// <remarks/>
        LM_SECURITYERROR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInventoryOverrides", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetInventoryOverridesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public int kListing;
        
        public GetInventoryOverridesRequest() {
        }
        
        public GetInventoryOverridesRequest(string Session, int kListing) {
            this.Session = Session;
            this.kListing = kListing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInventoryOverridesResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class GetInventoryOverridesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Inventory.lmReturnValue GetInventoryOverridesResult;
        
        public GetInventoryOverridesResponse() {
        }
        
        public GetInventoryOverridesResponse(LMWholesale.Inventory.lmReturnValue GetInventoryOverridesResult) {
            this.GetInventoryOverridesResult = GetInventoryOverridesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetInventoryOverrides", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class SetInventoryOverridesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public string Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=1)]
        public string dataIn;
        
        public SetInventoryOverridesRequest() {
        }
        
        public SetInventoryOverridesRequest(string Session, string dataIn) {
            this.Session = Session;
            this.dataIn = dataIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetInventoryOverridesResponse", WrapperNamespace="http://liquidmotors.com/webservices/", IsWrapped=true)]
    public partial class SetInventoryOverridesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://liquidmotors.com/webservices/", Order=0)]
        public LMWholesale.Inventory.lmReturnValue SetInventoryOverridesResult;
        
        public SetInventoryOverridesResponse() {
        }
        
        public SetInventoryOverridesResponse(LMWholesale.Inventory.lmReturnValue SetInventoryOverridesResult) {
            this.SetInventoryOverridesResult = SetInventoryOverridesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventorySoapChannel : LMWholesale.Inventory.InventorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventorySoapClient : System.ServiceModel.ClientBase<LMWholesale.Inventory.InventorySoap>, LMWholesale.Inventory.InventorySoap {
        
        public InventorySoapClient() {
        }
        
        public InventorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Inventory.GetInventoryOverridesResponse LMWholesale.Inventory.InventorySoap.GetInventoryOverrides(LMWholesale.Inventory.GetInventoryOverridesRequest request) {
            return base.Channel.GetInventoryOverrides(request);
        }
        
        public LMWholesale.Inventory.lmReturnValue GetInventoryOverrides(string Session, int kListing) {
            LMWholesale.Inventory.GetInventoryOverridesRequest inValue = new LMWholesale.Inventory.GetInventoryOverridesRequest();
            inValue.Session = Session;
            inValue.kListing = kListing;
            LMWholesale.Inventory.GetInventoryOverridesResponse retVal = ((LMWholesale.Inventory.InventorySoap)(this)).GetInventoryOverrides(inValue);
            return retVal.GetInventoryOverridesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Inventory.GetInventoryOverridesResponse> LMWholesale.Inventory.InventorySoap.GetInventoryOverridesAsync(LMWholesale.Inventory.GetInventoryOverridesRequest request) {
            return base.Channel.GetInventoryOverridesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Inventory.GetInventoryOverridesResponse> GetInventoryOverridesAsync(string Session, int kListing) {
            LMWholesale.Inventory.GetInventoryOverridesRequest inValue = new LMWholesale.Inventory.GetInventoryOverridesRequest();
            inValue.Session = Session;
            inValue.kListing = kListing;
            return ((LMWholesale.Inventory.InventorySoap)(this)).GetInventoryOverridesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LMWholesale.Inventory.SetInventoryOverridesResponse LMWholesale.Inventory.InventorySoap.SetInventoryOverrides(LMWholesale.Inventory.SetInventoryOverridesRequest request) {
            return base.Channel.SetInventoryOverrides(request);
        }
        
        public LMWholesale.Inventory.lmReturnValue SetInventoryOverrides(string Session, string dataIn) {
            LMWholesale.Inventory.SetInventoryOverridesRequest inValue = new LMWholesale.Inventory.SetInventoryOverridesRequest();
            inValue.Session = Session;
            inValue.dataIn = dataIn;
            LMWholesale.Inventory.SetInventoryOverridesResponse retVal = ((LMWholesale.Inventory.InventorySoap)(this)).SetInventoryOverrides(inValue);
            return retVal.SetInventoryOverridesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LMWholesale.Inventory.SetInventoryOverridesResponse> LMWholesale.Inventory.InventorySoap.SetInventoryOverridesAsync(LMWholesale.Inventory.SetInventoryOverridesRequest request) {
            return base.Channel.SetInventoryOverridesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LMWholesale.Inventory.SetInventoryOverridesResponse> SetInventoryOverridesAsync(string Session, string dataIn) {
            LMWholesale.Inventory.SetInventoryOverridesRequest inValue = new LMWholesale.Inventory.SetInventoryOverridesRequest();
            inValue.Session = Session;
            inValue.dataIn = dataIn;
            return ((LMWholesale.Inventory.InventorySoap)(this)).SetInventoryOverridesAsync(inValue);
        }
    }
}
